// Auto-generated from docs/drafts/resources-glossary.md.
// To update, edit the markdown draft and regenerate.

export type GlossaryCategory = 'Carrier' | 'Customs' | 'Operational' | 'Technical' | 'Regulatory';

export interface GlossaryEntry {
  slug: string;
  name: string;
  code?: string;
  category: GlossaryCategory;
  definition: string;
  context: string;
  related?: string;
}

export const GLOSSARY_ENTRIES: GlossaryEntry[] = [
  {
    slug: "buy-shipping-amazon",
    name: "Buy Shipping (Amazon)",
    category: "Carrier",
    definition: "Amazon's discounted shipping rates available only for orders placed on Amazon, bought through Seller Central or an integrated platform.",
    context: "Amazon Buy Shipping covers a limited carrier list (Royal Mail, Amazon Shipping, Evri, and a handful of others) at negotiated rates. It is cheap for Amazon orders and useless for everything else. Sellers running Amazon plus eBay, Etsy, or Shopify need a multi-carrier platform that includes Amazon Buy Shipping inside a wider queue.",
    related: "[Seller Fulfilled Prime](#seller-fulfilled-prime-sfp), [Valid Tracking Rate](#valid-tracking-rate-vtr), [/solutions/marketplace-seller](/solutions/marketplace-seller)",
  },
  {
    slug: "carrier-portal",
    name: "Carrier portal",
    category: "Carrier",
    definition: "The website a carrier provides for booking shipments, printing labels, and tracking parcels for a single account.",
    context: "Every UK shipper recognises the pattern. Royal Mail Click and Drop, DPD Shipping Portal, Evri Business, DHL MyDHL+, Amazon Seller Central. A business shipping through four carriers logs into four portals. Multi-carrier platforms replace the portal stack with one queue.",
    related: "[Multi-carrier](#multi-carrier), [Rate engine](#rate-engine), [/connexx](/connexx)",
  },
  {
    slug: "child-account",
    name: "Child account",
    category: "Carrier",
    definition: "A sub-account under a parent carrier contract, typically used by 3PLs to give each brand client its own rate card, reporting, and labels.",
    context: "A 3PL holds the master agreement with Royal Mail, DPD, Evri, or DHL and creates a child account per brand client. Each child account has its own rate card, its own dispatch rules, and its own branded tracking page. Connexx manages unlimited child accounts under one parent contract, with billing and SLAs tracked per client.",
    related: "[Multi-carrier](#multi-carrier), [Rate card](#rate-card), [/solutions/3pl](/solutions/3pl)",
  },
  {
    slug: "click-and-drop-royal-mail",
    name: "Click and Drop (Royal Mail)",
    category: "Carrier",
    definition: "Royal Mail's free online shipping tool for printing labels and booking collections.",
    context: "Click and Drop is the default starting point for UK small businesses on Royal Mail. It works for Royal Mail-only operations. Once a business adds Evri, DPD, or Parcelforce, the workflow fragments and the team starts juggling portals.",
    related: "[Carrier portal](#carrier-portal), [Multi-carrier](#multi-carrier), [Royal Mail Tracked 24/48](#royal-mail-tracked-2448)",
  },
  {
    slug: "drop-off-parcelshop-locker",
    name: "Drop-off (ParcelShop, locker)",
    category: "Carrier",
    definition: "A delivery option where the parcel is dropped at a third-party location (shop or locker) rather than collected from the sender or delivered to a residence.",
    context: "Evri ParcelShop, InPost lockers, and Royal Mail Customer Service Points are the main UK drop-off networks. Drop-off rates are typically 30 to 40 per cent cheaper than door collection. Most consumer eCommerce brands offer drop-off as a low-cost delivery tier at checkout.",
    related: "[Out-of-area](#out-of-area), [Surcharge zone](#surcharge-zone)",
  },
  {
    slug: "fuel-surcharge",
    name: "Fuel surcharge",
    category: "Carrier",
    definition: "A variable cost line every carrier adds to base shipping rates to cover diesel and aviation fuel price movement.",
    context: "Royal Mail, DPD, DHL, FedEx, UPS, and the pallet networks all publish a monthly fuel surcharge as a percentage of the base rate. It changes month to month. Carrier portals show it in the invoice. A rate engine has to pull the live surcharge to compare carriers honestly.",
    related: "[Rate card](#rate-card), [Negotiated rate](#negotiated-rate), [Surcharge zone](#surcharge-zone)",
  },
  {
    slug: "highlands-islands",
    name: "Highlands & Islands",
    category: "Carrier",
    definition: "The UK surcharge zone covering the Scottish Highlands, Scottish islands, Isle of Man, and the Channel Islands, where every major carrier applies an additional fee.",
    context: "Every UK shipper knows the Highlands surcharge. A parcel from London to Inverness costs more than London to Glasgow on most carriers. The postcode prefixes that trigger the surcharge are published by each carrier and change occasionally. Routing rules in a multi-carrier platform apply the right carrier per postcode automatically.",
    related: "[Out-of-area](#out-of-area), [Surcharge zone](#surcharge-zone), [Mainland UK](#mainland-uk)",
  },
  {
    slug: "late-shipment-rate-lsr",
    name: "Late Shipment Rate (LSR)",
    code: "LSR",
    category: "Carrier",
    definition: "An Amazon and eBay seller metric tracking the percentage of orders dispatched after the platform's deadline.",
    context: "Amazon's LSR threshold is 4 per cent. Cross it and your seller account is at risk of suspension. The metric is unforgiving because it covers every order shipped from your seller account, including orders missed during a system outage or a carrier strike. Velocity Sellers eliminated penalty fees by switching to SLA-aware carrier routing in Connexx.",
    related: "[Valid Tracking Rate](#valid-tracking-rate-vtr), [On-Time Delivery Rate](#on-time-delivery-rate-otdr), [/solutions/marketplace-seller](/solutions/marketplace-seller)",
  },
  {
    slug: "mainland-uk",
    name: "Mainland UK",
    category: "Carrier",
    definition: "The carrier zone covering England, Wales, and mainland Scotland, excluding the Highlands, Islands, Channel Islands, and Northern Ireland.",
    context: "Mainland UK is the base zone. Highlands & Islands, Channel Islands, Northern Ireland, and BFPO addresses each carry surcharges or different routing. Carrier rate cards quote a Mainland UK price and then list the surcharge zones separately.",
    related: "[Highlands & Islands](#highlands--islands), [Out-of-area](#out-of-area), [Surcharge zone](#surcharge-zone)",
  },
  {
    slug: "multi-carrier",
    name: "Multi-carrier",
    category: "Carrier",
    definition: "A shipping setup that connects one business to two or more parcel carriers from a single platform, with rate comparison between them per order.",
    context: "The product category Connexx belongs to. A multi-carrier platform compares live rates across Royal Mail, DPD, Evri, Parcelforce, DHL, FedEx, UPS, Amazon Shipping, and others on every shipment, picks the cheapest compliant option, and generates the label in one click. The alternative is logging into each carrier's portal separately.",
    related: "[Rate engine](#rate-engine), [Negotiated rate](#negotiated-rate), [/connexx](/connexx)",
  },
  {
    slug: "negotiated-rate",
    name: "Negotiated rate",
    category: "Carrier",
    definition: "A carrier rate lower than the published rack rate, available to high-volume shippers or to platforms that aggregate volume across many customers.",
    context: "Royal Mail, DPD, Evri, and DHL all negotiate rates against committed volume. A small business shipping 50 parcels a day will not get a negotiated rate directly. A platform like Connexx aggregates volume across thousands of shippers and passes the negotiated rates down to every customer, regardless of individual volume.",
    related: "[Rack rate](#rack-rate), [Rate card](#rate-card), [Multi-carrier](#multi-carrier)",
  },
  {
    slug: "on-time-delivery-rate-otdr",
    name: "On-Time Delivery Rate (OTDR)",
    code: "OTDR",
    category: "Carrier",
    definition: "An Amazon seller metric tracking the percentage of orders delivered by the promised delivery date.",
    context: "OTDR is Amazon's newer SLA metric, complementing Valid Tracking Rate and Late Shipment Rate. The threshold is 92 per cent. Carrier choice, dispatch cutoff, and weather all affect it. A multi-carrier platform routes Amazon orders through carriers with strong OTDR performance on the specific lane and weight tier.",
    related: "[Valid Tracking Rate](#valid-tracking-rate-vtr), [Late Shipment Rate](#late-shipment-rate-lsr), [/solutions/marketplace-seller](/solutions/marketplace-seller)",
  },
  {
    slug: "out-of-area",
    name: "Out-of-area",
    category: "Carrier",
    definition: "A postcode outside a carrier's standard delivery zone, where the carrier applies a surcharge or refuses the shipment.",
    context: "Every UK carrier publishes an out-of-area postcode list. Highlands, Islands, Channel Islands, and Northern Ireland are the common ones. DPD and Evri each have slightly different lists, which is why an automated routing rule beats a manual choice. A wrong out-of-area decision costs a redelivery charge or a returned parcel.",
    related: "[Highlands & Islands](#highlands--islands), [Surcharge zone](#surcharge-zone), [Mainland UK](#mainland-uk)",
  },
  {
    slug: "pod-proof-of-delivery",
    name: "POD (Proof of Delivery)",
    category: "Carrier",
    definition: "Evidence that a parcel was delivered, usually a signature or photograph captured by the carrier driver at the delivery address.",
    context: "B2B shipments depend on POD because the buyer expects evidence the consignment arrived intact. DPD, DHL, UPS, and the pallet networks all capture signature or photo POD by default. Connexx pulls POD events back into the ERP automatically so finance and customer service can answer disputes without logging into a carrier portal.",
    related: "[SLA](#sla-service-level-agreement), [Tracking number](#tracking-number--consignment-reference), [/solutions/b2b](/solutions/b2b)",
  },
  {
    slug: "rack-rate",
    name: "Rack rate",
    category: "Carrier",
    definition: "A carrier's published list price for a shipment, before any negotiated discount.",
    context: "Rack rates are the rates a small or new shipper pays unless they negotiate. Royal Mail publishes Business Account rack rates. DPD publishes a public rate card. Volume buyers and aggregator platforms negotiate below rack. The gap between rack and negotiated is where Connexx saves money for small and mid-market shippers.",
    related: "[Negotiated rate](#negotiated-rate), [Rate card](#rate-card)",
  },
  {
    slug: "rate-card",
    name: "Rate card",
    category: "Carrier",
    definition: "The price schedule for a carrier's services, broken down by weight tier, destination zone, and service speed.",
    context: "Every carrier has a rate card. Royal Mail's is structured by service (Tracked 24, Tracked 48, Special Delivery), weight band, and destination. DPD's adds size-based dim weight. A 3PL holds a rate card per client. Rate cards change at least annually and often quarterly.",
    related: "[Rack rate](#rack-rate), [Negotiated rate](#negotiated-rate), [Rate engine](#rate-engine)",
  },
  {
    slug: "rate-engine",
    name: "Rate engine",
    category: "Carrier",
    definition: "The component of a shipping platform that compares carrier rates in real time on every shipment and picks the optimal carrier against pre-set rules.",
    context: "A rate engine takes a shipment (weight, dimensions, destination, service required) and runs it against every active carrier's rate card and routing logic. Connexx's rate engine evaluates every carrier on every order in under 200 milliseconds. The output is a ranked list of compliant carriers with their cost and SLA.",
    related: "[Multi-carrier](#multi-carrier), [Rate card](#rate-card), [/connexx](/connexx)",
  },
  {
    slug: "royal-mail-tracked-24-48",
    name: "Royal Mail Tracked 24/48",
    category: "Carrier",
    definition: "Royal Mail's tracked parcel services, with target delivery in one working day (Tracked 24) or two working days (Tracked 48).",
    context: "Tracked 24 and Tracked 48 are the workhorses of UK eCommerce. They cover every UK postcode, push scan events back to Amazon and other marketplaces within the SLA, and qualify for Amazon Seller Fulfilled Prime. Most UK retailers ship sub-2kg orders on Tracked 48 by default.",
    related: "[Buy Shipping](#buy-shipping-amazon), [Seller Fulfilled Prime](#seller-fulfilled-prime-sfp), [Valid Tracking Rate](#valid-tracking-rate-vtr)",
  },
  {
    slug: "saturday-delivery",
    name: "Saturday delivery",
    category: "Carrier",
    definition: "A delivery service that operates on Saturdays, usually carrying an additional surcharge above weekday rates.",
    context: "DPD Saturday, Parcelforce Saturday, and Royal Mail Special Delivery all offer Saturday delivery. The surcharge is meaningful (typically \u00a33 to \u00a37 above the weekday rate). Multi-carrier platforms apply Saturday routing only when the customer paid for it at checkout, not by default.",
    related: "[SLA](#sla-service-level-agreement), [Rate card](#rate-card)",
  },
  {
    slug: "seller-fulfilled-prime-sfp",
    name: "Seller Fulfilled Prime (SFP)",
    code: "SFP",
    category: "Carrier",
    definition: "An Amazon programme that lets sellers offer Prime two-day delivery from their own warehouse, instead of Amazon FBA, using Amazon-approved carriers.",
    context: "SFP requires sellers to meet strict performance thresholds (Valid Tracking Rate, Late Shipment Rate, On-Time Delivery Rate) and ship through approved carriers (Royal Mail Tracked 24, Amazon Shipping, DPD Next Day, and a small list of others). Sellers running SFP need carrier routing that defaults to the approved list and falls back gracefully when an order does not meet the criteria.",
    related: "[Buy Shipping](#buy-shipping-amazon), [Valid Tracking Rate](#valid-tracking-rate-vtr), [/solutions/marketplace-seller](/solutions/marketplace-seller)",
  },
  {
    slug: "sla-service-level-agreement",
    name: "SLA (Service Level Agreement)",
    category: "Carrier",
    definition: "The carrier's contractual delivery promise, typically expressed as a target delivery time (e.g. next working day before 12pm) and a percentage of shipments delivered within it.",
    context: "SLAs vary by service, by destination, and by carrier. DPD Next Day Before 12 is a different SLA from DPD Next Day. Carrier SLA data feeds into a multi-carrier platform's routing logic and into the customer-facing delivery promise at checkout. Missed SLAs are the source of most customer service tickets.",
    related: "[POD](#pod-proof-of-delivery), [WISMO](#wismo-where-is-my-order), [Late Shipment Rate](#late-shipment-rate-lsr)",
  },
  {
    slug: "tracking-number-consignment-reference",
    name: "Tracking number / consignment reference",
    category: "Carrier",
    definition: "The unique identifier the carrier assigns to a parcel or consignment, used to look up its status at any point in the journey.",
    context: "Royal Mail uses a 13-character reference. DPD uses a 14-digit number. UPS uses 1Z followed by 16 characters. Each carrier's format is different. Connexx normalises tracking numbers into a single field per order and writes them back to Shopify, Amazon, eBay, or your ERP automatically.",
    related: "[POD](#pod-proof-of-delivery), [WISMO](#wismo-where-is-my-order), [ERP write-back](#erp-write-back)",
  },
  {
    slug: "valid-tracking-rate-vtr",
    name: "Valid Tracking Rate (VTR)",
    code: "VTR",
    category: "Carrier",
    definition: "An Amazon seller metric tracking the percentage of orders dispatched with a valid tracking number that scans within the SLA window.",
    context: "Amazon's VTR threshold is 95 per cent. Carriers that scan parcels on collection (Royal Mail Tracked 24/48, Amazon Shipping, DPD) meet VTR cleanly. Non-tracked services do not. Connexx routes Amazon orders through VTR-compliant carriers by default and writes the tracking number back to Seller Central before the dispatch deadline.",
    related: "[Late Shipment Rate](#late-shipment-rate-lsr), [On-Time Delivery Rate](#on-time-delivery-rate-otdr), [Seller Fulfilled Prime](#seller-fulfilled-prime-sfp)\n\n---",
  },
  {
    slug: "ata-carnet",
    name: "ATA Carnet",
    category: "Customs",
    definition: "An international customs document that allows temporary import of goods (samples, professional equipment, exhibition stock) into a country without paying duty.",
    context: "ATA Carnets are issued by chambers of commerce in the goods' home country. UK exporters use them for trade shows, demo equipment, and broadcast kit. The carnet has a one-year validity and is presented at customs in both directions. Connexx flags carnet-eligible shipments at the point of booking.",
    related: "[Customs declaration](#cds-customs-declaration-service), [HS code](#hs-code-harmonised-system-code)",
  },
  {
    slug: "atr-movement-certificate-eu-turkey",
    name: "ATR (movement certificate, EU-Turkey)",
    category: "Customs",
    definition: "A movement certificate proving that goods qualify for preferential customs treatment under the EU-Turkey Customs Union.",
    context: "An ATR is required for shipments between the EU and Turkey to benefit from zero or reduced duty. Without it, standard tariffs apply. UK exporters to Turkey now need an ATR plus a UK-Turkey trade agreement document depending on the goods category. Connexx generates ATRs automatically for Turkey-bound shipments.",
    related: "[EUR.1](#eur1-movement-certificate), [Rules of origin](#rules-of-origin), [/solutions/export](/solutions/export)",
  },
  {
    slug: "c79-vat-certificate",
    name: "C79 (VAT certificate)",
    category: "Customs",
    definition: "A monthly certificate from HMRC showing the import VAT a UK business has paid through CHIEF or CDS, used to reclaim VAT on the next return.",
    context: "Importers using Postponed VAT Accounting receive a C79 from HMRC each month. The figure has to be reconciled against accounting records before submitting the VAT return. Connexx reconciles the C79 against shipment-level import VAT data automatically and exports the result to the finance system.",
    related: "[Postponed VAT Accounting](#pva-postponed-vat-accounting), [Duty deferment](#duty-deferment), [/solutions/import](/solutions/import)",
  },
  {
    slug: "cds-customs-declaration-service",
    name: "CDS (Customs Declaration Service)",
    category: "Customs",
    definition: "HMRC's customs declaration platform, used by UK importers, exporters, and customs brokers to submit declarations to UK customs.",
    context: "CDS replaced CHIEF in 2023 for imports and 2024 for exports. Every UK customs declaration now flows through CDS, either submitted directly by the trader or filed by a customs broker on their behalf. Connexx connects to CDS through certified intermediaries and submits declarations before goods arrive at the port.",
    related: "[CHIEF](#chief-legacy-uk-customs-system), [Pre-clearance](#pre-clearance), [EORI](#eori-economic-operators-registration-and-identification)",
  },
  {
    slug: "certificate-of-origin",
    name: "Certificate of origin",
    category: "Customs",
    definition: "A document declaring the country where goods were produced, required by certain importing countries for customs clearance or to qualify for preferential duty.",
    context: "Certificates of origin are issued by chambers of commerce or generated from the trader's own records. Some destinations (Saudi Arabia, Egypt, India, several African markets) require chamber-issued certificates. Others accept self-certification. Connexx generates the correct document type per destination automatically.",
    related: "[EUR.1](#eur1-movement-certificate), [Rules of origin](#rules-of-origin), [Commercial invoice](#commercial-invoice)",
  },
  {
    slug: "chief-legacy-uk-customs-system",
    name: "CHIEF (legacy UK customs system)",
    category: "Customs",
    definition: "HMRC's previous customs declaration platform, replaced by CDS for imports in 2023 and exports in 2024.",
    context: "CHIEF was the UK customs backbone for decades. CDS replaced it in stages. Any software stack that has not migrated from CHIEF to CDS is out of date. Connexx submits declarations through CDS from day one.",
    related: "[CDS](#cds-customs-declaration-service), [HMRC](#hmrc), [Pre-clearance](#pre-clearance)",
  },
  {
    slug: "commercial-invoice",
    name: "Commercial invoice",
    category: "Customs",
    definition: "The document showing the commercial value of an international shipment, used by customs to assess duty and VAT.",
    context: "Every international shipment needs a commercial invoice. It lists the goods, the HS code, the unit value, the seller, the buyer, the EORI numbers, and the Incoterms. A wrong line on the commercial invoice triggers a customs hold. Connexx generates commercial invoices from the sales order data automatically so the figures match across the documentation pack.",
    related: "[Packing list](#packing-list), [HS code](#hs-code-harmonised-system-code), [EORI](#eori-economic-operators-registration-and-identification)",
  },
  {
    slug: "ddp-delivered-duty-paid",
    name: "DDP (Delivered Duty Paid)",
    category: "Customs",
    definition: "An Incoterm where the seller pays the duty and import VAT, and the goods arrive at the buyer with no customs charges to pay on delivery.",
    context: "DDP is the eCommerce-friendly Incoterm for cross-border B2C. The customer sees the final landed price at checkout and the parcel arrives with no surprises. DDP requires the seller to know the duty rate, calculate it at checkout, and pass it to the carrier. DHL Express, DPD Cross-Border, and a handful of others support DDP at the parcel level.",
    related: "[Incoterms](#incoterms), [DDU](#ddu-delivered-duty-unpaid), [Landed cost](#landed-cost)",
  },
  {
    slug: "ddu-delivered-duty-unpaid",
    name: "DDU (Delivered Duty Unpaid)",
    category: "Customs",
    definition: "An Incoterm where the seller delivers the goods to the buyer's country but the buyer pays import duty and VAT on arrival.",
    context: "DDU is the cheapest Incoterm for the seller and the worst for the customer. The customer gets an unexpected bill on the doorstep. For B2C cross-border, DDU drives complaints and refused deliveries. Most carriers no longer use the term DDU, having moved to DAP (Delivered at Place) under Incoterms 2020, but the legacy term is still common.",
    related: "[DDP](#ddp-delivered-duty-paid), [Incoterms](#incoterms), [Landed cost](#landed-cost)",
  },
  {
    slug: "duty",
    name: "Duty",
    category: "Customs",
    definition: "A tax charged by a country on imported goods, calculated as a percentage of the goods' customs value (usually the commercial invoice value plus freight and insurance).",
    context: "Duty rates depend on the HS code and the country of origin. The UK Global Tariff publishes UK import duty rates. EU duty rates are published in the EU's TARIC database. Duty is paid by the importer of record, not the carrier. Connexx calculates duty per SKU against the live tariff before goods arrive.",
    related: "[HS code](#hs-code-harmonised-system-code), [UK Global Tariff](#uk-global-tariff), [Landed cost](#landed-cost)",
  },
  {
    slug: "duty-deferment",
    name: "Duty deferment",
    category: "Customs",
    definition: "An HMRC scheme allowing approved UK importers to defer duty and import VAT payment until the 15th of the following month, paid via direct debit.",
    context: "A Duty Deferment Account (DDA) is essential for any importer doing meaningful volume. It avoids the cash drag of paying duty at every clearance and consolidates payment into one monthly direct debit. Setting up a DDA requires a guarantee from a bank or insurer. Connexx links to your DDA for automatic deferment on every import.",
    related: "[Postponed VAT Accounting](#pva-postponed-vat-accounting), [C79](#c79-vat-certificate), [HMRC](#hmrc)",
  },
  {
    slug: "duty-drawback",
    name: "Duty drawback",
    category: "Customs",
    definition: "A refund of import duty paid on goods that are subsequently re-exported from the country, often used by businesses that import components and export finished products.",
    context: "Duty drawback is a cash flow benefit for businesses that import to manufacture and re-export. Claims are made via HMRC against documented imports and matched exports. The paperwork burden is real, which is why many businesses leave money on the table. Connexx tags drawback-eligible shipments and exports the data set for the claim.",
    related: "[Duty](#duty), [Inward Processing Relief](#ipr-inward-processing-relief)",
  },
  {
    slug: "eori-economic-operators-registration-and-identification",
    name: "EORI (Economic Operators Registration and Identification)",
    category: "Customs",
    definition: "The unique identifier issued by HMRC (or any EU customs authority) to a business that imports or exports goods, used on every customs declaration.",
    context: "A UK EORI starts with GB. An EU EORI starts with the country code (DE, FR, IE, and so on). UK exporters to the EU need both, or use the importer's EU EORI under DDP. EORIs are applied for at gov.uk and issued in about three working days. Connexx stores GB and EU EORIs per legal entity and applies the right one per shipment.",
    related: "[HMRC](#hmrc), [Commercial invoice](#commercial-invoice), [IOSS](#ioss-import-one-stop-shop), [/solutions/export](/solutions/export)",
  },
  {
    slug: "eur-1-movement-certificate",
    name: "EUR.1 (movement certificate)",
    category: "Customs",
    definition: "A movement certificate proving goods qualify for preferential duty treatment under the UK-EU Trade and Cooperation Agreement or other preferential trade deals.",
    context: "An EUR.1 is required to claim zero duty on UK origin goods entering the EU (or vice versa) above certain consignment values. Below the threshold, a statement on origin on the commercial invoice is enough. Misclaiming origin leads to retrospective duty and penalties. Connexx checks origin claims against the trader's bill of materials before generating the certificate.",
    related: "[ATR](#atr-movement-certificate-eu-turkey), [Rules of origin](#rules-of-origin), [Certificate of origin](#certificate-of-origin)",
  },
  {
    slug: "hmrc",
    name: "HMRC",
    category: "Customs",
    definition: "His Majesty's Revenue and Customs, the UK government department responsible for tax collection and customs.",
    context: "HMRC operates CDS, issues UK EORIs, runs the Duty Deferment scheme, and publishes the UK Global Tariff. Every UK importer and exporter interacts with HMRC, directly or through a customs broker. Connexx connects to HMRC services through certified intermediaries.",
    related: "[CDS](#cds-customs-declaration-service), [EORI](#eori-economic-operators-registration-and-identification), [UK Global Tariff](#uk-global-tariff)",
  },
  {
    slug: "hs-code-harmonised-system-code",
    name: "HS code (Harmonised System code)",
    category: "Customs",
    definition: "A globally standardised numeric code (six digits internationally, ten in the UK and EU) that classifies a product for customs and duty purposes.",
    context: "Every international shipment needs an HS code. The first six digits are common across 200+ countries (set by the World Customs Organization). The next four are country-specific. The UK Global Tariff and the EU's TARIC database hold the duty rate and import controls keyed off each code. Misclassification causes customs holds and incorrect duty payment. Connexx suggests an HS code from the product description and stores the SKU-to-HS mapping for future shipments.",
    related: "[Tariff classification](#tariff-classification), [UK Global Tariff](#uk-global-tariff), [Commercial invoice](#commercial-invoice)",
  },
  {
    slug: "incoterms",
    name: "Incoterms",
    category: "Customs",
    definition: "The International Chamber of Commerce's set of standardised trade terms (DDP, DAP, FCA, EXW, and others) that define who pays for shipping, insurance, and duty on a cross-border sale.",
    context: "Every international sales contract specifies an Incoterm. Incoterms 2020 is the current version. The two most common in eCommerce are DDP (seller pays everything) and DAP (buyer pays duty on delivery). The two most common in B2B are FCA (seller delivers to a named carrier) and EXW (buyer collects). Connexx applies the agreed Incoterm to every shipment automatically.",
    related: "[DDP](#ddp-delivered-duty-paid), [DDU](#ddu-delivered-duty-unpaid), [Landed cost](#landed-cost)",
  },
  {
    slug: "ioss-import-one-stop-shop",
    name: "IOSS (Import One-Stop Shop)",
    category: "Customs",
    definition: "An EU VAT scheme that lets non-EU sellers charge EU VAT at checkout on B2C consignments under \u20ac150 and remit it monthly via one EU member state, avoiding VAT collection on delivery.",
    context: "IOSS applies to consignments under \u20ac150 sold to EU consumers. The seller registers in any EU member state, charges the destination country's VAT at checkout, and files one monthly IOSS return. The customer pays no extra VAT on delivery. Above \u20ac150, standard import VAT applies. Connexx applies the trader's IOSS number to every qualifying shipment and routes through IOSS-compatible carriers.",
    related: "[OSS](#oss-one-stop-shop), [EORI](#eori-economic-operators-registration-and-identification), [DDP](#ddp-delivered-duty-paid), [/solutions/export](/solutions/export)",
  },
  {
    slug: "oss-one-stop-shop",
    name: "OSS (One-Stop Shop)",
    category: "Customs",
    definition: "An EU VAT scheme that lets EU-resident businesses report VAT on B2C cross-border EU sales through one quarterly return in their home member state.",
    context: "OSS is for EU businesses selling cross-border within the EU. IOSS is for non-EU businesses selling into the EU. A UK seller with an EU establishment can use OSS for intra-EU B2C sales. Both schemes simplify VAT reporting but require accurate consignment-level data.",
    related: "[IOSS](#ioss-import-one-stop-shop), [EORI](#eori-economic-operators-registration-and-identification)",
  },
  {
    slug: "packing-list",
    name: "Packing list",
    category: "Customs",
    definition: "A document listing the contents of a shipment by line, used by customs to verify the commercial invoice and by warehouses to check goods on arrival.",
    context: "The packing list and the commercial invoice have to match exactly. A discrepancy on weight, count, or description triggers a customs query that can hold the shipment for two days. Connexx generates both documents from the same source data so they cannot disagree.",
    related: "[Commercial invoice](#commercial-invoice), [HS code](#hs-code-harmonised-system-code)",
  },
  {
    slug: "phytosanitary-certificate",
    name: "Phytosanitary certificate",
    category: "Customs",
    definition: "An official certificate confirming that plant-based goods or related products meet the importing country's plant health requirements.",
    context: "Phytosanitary certificates are issued by the Animal and Plant Health Agency (APHA) in the UK. Goods covered include fresh produce, timber, wooden packaging, and many plant-derived ingredients. The certificate is required at the border. Missing it stops the shipment.",
    related: "[Pre-clearance](#pre-clearance), [Certificate of origin](#certificate-of-origin)",
  },
  {
    slug: "pre-clearance",
    name: "Pre-clearance",
    category: "Customs",
    definition: "Submitting and approving a customs declaration before the goods arrive at the border, so the shipment clears on arrival rather than waiting for the declaration to be processed.",
    context: "Pre-clearance is the difference between a same-day clearance and a 48-hour delay. The declaration is filed against the manifest data before the truck or container reaches the port. Connexx pre-clears every import declaration on CDS as soon as the manifest is generated, so goods clear on arrival. Northgate Imports cut customs delays 60 per cent and lifted duty cost accuracy from 82 per cent to 97 per cent using this.",
    related: "[CDS](#cds-customs-declaration-service), [Customs hold](#customs-hold), [/solutions/import](/solutions/import)",
  },
  {
    slug: "pva-postponed-vat-accounting",
    name: "PVA (Postponed VAT Accounting)",
    category: "Customs",
    definition: "A UK scheme that lets registered importers account for import VAT on the next VAT return instead of paying it at the border.",
    context: "PVA is a cash flow win. Import VAT is no longer paid at the point of import and reclaimed later. It is declared and reclaimed on the same VAT return. The C79 certificate is replaced by a monthly statement on the trader's CDS account. Connexx flags every shipment as PVA-eligible by default and reconciles against the monthly statement.",
    related: "[C79](#c79-vat-certificate), [Duty deferment](#duty-deferment), [/solutions/import](/solutions/import)",
  },
  {
    slug: "rules-of-origin",
    name: "Rules of origin",
    category: "Customs",
    definition: "The criteria a country uses to determine where goods were produced, which decides whether they qualify for preferential duty under a trade agreement.",
    context: "Under the UK-EU TCA, goods of UK or EU origin qualify for zero duty if they meet the rules of origin (typically a percentage of value added in the country, or a change in tariff heading). Misclaiming origin leads to retrospective duty and penalties. Connexx checks origin claims against the bill of materials for every export.",
    related: "[EUR.1](#eur1-movement-certificate), [Certificate of origin](#certificate-of-origin), [Duty](#duty)",
  },
  {
    slug: "tariff-classification",
    name: "Tariff classification",
    category: "Customs",
    definition: "The process of assigning the correct HS code to a product, against the UK Global Tariff (for imports) or the destination country's tariff (for exports).",
    context: "Classification is harder than it looks. Many products fall into multiple plausible codes. The wrong code can cost a percentage point of duty or trigger an import licence requirement. Connexx classifies from the product description and validates against the UK Global Tariff, storing the SKU-to-HS mapping for future shipments.",
    related: "[HS code](#hs-code-harmonised-system-code), [UK Global Tariff](#uk-global-tariff)",
  },
  {
    slug: "uk-global-tariff",
    name: "UK Global Tariff",
    category: "Customs",
    definition: "The UK's post-Brexit import tariff, published by HMRC, setting the duty rate and import controls for every HS code on goods entering the UK.",
    context: "The UK Global Tariff (UKGT) replaced the EU's Common External Tariff after Brexit. Many lines were liberalised (zero duty), others retained the EU rate, and some changed structure. Connexx pulls the live UKGT for every import to calculate landed cost.",
    related: "[HS code](#hs-code-harmonised-system-code), [Duty](#duty), [Landed cost](#landed-cost)",
  },
  {
    slug: "windsor-framework",
    name: "Windsor Framework",
    category: "Customs",
    definition: "The 2023 agreement between the UK and the EU that governs the movement of goods between Great Britain and Northern Ireland, replacing parts of the Northern Ireland Protocol.",
    context: "The Windsor Framework introduced the Green Lane (for goods staying in Northern Ireland) and the Red Lane (for goods at risk of moving into the EU). Green Lane goods clear with minimal customs checks. Red Lane goods follow full EU import procedures. Connexx routes Northern Ireland shipments through the correct lane automatically.",
    related: "[CDS](#cds-customs-declaration-service), [EORI](#eori-economic-operators-registration-and-identification), [/solutions/import](/solutions/import)\n\n---",
  },
  {
    slug: "consolidation",
    name: "Consolidation",
    category: "Operational",
    definition: "Combining multiple smaller shipments into one larger shipment to lower per-unit cost, often used in freight and pallet networks.",
    context: "A 3PL consolidating client deliveries at a hub before final-mile dispatch is one example. Importers consolidating supplier orders into a single container is another. Consolidation cuts cost and increases complexity. Connexx tracks consolidated shipments back to the underlying orders so per-client billing stays accurate.",
    related: "[Manifest](#manifest), [Lane](#lane)",
  },
  {
    slug: "csat",
    name: "CSAT",
    category: "Operational",
    definition: "Customer Satisfaction score, typically measured by post-delivery survey on a 1-to-5 or 1-to-10 scale.",
    context: "WISMO tickets and delivery exceptions are the biggest drivers of CSAT drops in eCommerce. A clean delivery experience holds CSAT. Repeated tracking failures erode it within a week. Multi-carrier platforms protect CSAT by routing each order through the most reliable carrier on that lane.",
    related: "[WISMO](#wismo-where-is-my-order), [SLA](#sla-service-level-agreement)",
  },
  {
    slug: "dimensional-weight-dim-weight",
    name: "Dimensional weight (DIM weight)",
    category: "Operational",
    definition: "A pricing weight calculated from a parcel's volume rather than its actual weight, used by carriers to price lightweight but bulky shipments.",
    context: "DIM weight is the carrier's defence against being paid to ship empty space. The formula is length x width x height divided by a divisor (typically 5,000 or 6,000 for international, 4,000 for some UK domestic). The carrier charges by the higher of actual or dimensional weight. Connexx applies DIM rules per carrier so the rate engine compares like with like.",
    related: "[Volumetric weight](#volumetric-weight), [Rate card](#rate-card)",
  },
  {
    slug: "dispatch",
    name: "Dispatch",
    category: "Operational",
    definition: "The act of preparing and sending a shipment, including label generation, manifest creation, and handover to the carrier.",
    context: "Dispatch is the verb every UK operator uses. \"Dispatch decisions\", \"dispatch team\", \"dispatch volume\", \"dispatch cutoff\". A dispatch cutoff is the time by which a parcel has to be handed to the carrier to be collected that day. Miss it and the parcel ships tomorrow.",
    related: "[Manifest](#manifest), [SLA](#sla-service-level-agreement), [Late Shipment Rate](#late-shipment-rate-lsr)",
  },
  {
    slug: "fcl-lcl-full-less-than-container-load",
    name: "FCL / LCL (Full / Less than Container Load)",
    category: "Operational",
    definition: "Sea freight shipping modes where FCL means the shipment fills a 20ft or 40ft container, and LCL means it shares a container with other shippers.",
    context: "FCL is faster and cheaper per cubic metre at high volume. LCL is the option for smaller importers who cannot fill a container. Most UK importers from Asia run LCL until they hit consistent container volume. Connexx integrates with freight forwarders for both modes.",
    related: "[LTL](#ltl-less-than-truckload), [Consolidation](#consolidation), [/solutions/import](/solutions/import)",
  },
  {
    slug: "lane",
    name: "Lane",
    category: "Operational",
    definition: "A specific shipping route, usually expressed as origin country to destination country (e.g. UK to Germany, UK to US), with implications for carrier choice, transit time, and customs treatment.",
    context: "\"Lane\" is the planning unit for an export or international eCommerce operation. The UK-to-Germany lane needs a different carrier mix from UK-to-US. Lane performance is measured in cost per parcel, transit time, and exception rate. Connexx tracks lane-level performance per carrier in the dashboard.",
    related: "[Carrier portal](#carrier-portal), [Consolidation](#consolidation), [SLA](#sla-service-level-agreement)",
  },
  {
    slug: "ltl-less-than-truckload",
    name: "LTL (Less Than Truckload)",
    category: "Operational",
    definition: "A road freight mode for shipments too large for parcel carriers but too small to fill a truck, typically used for palletised goods through pallet networks.",
    context: "UK LTL runs through pallet networks like Pall-Ex, Palletline, and Palletways. A shipment is collected, taken to a hub, sorted, and trunked to the destination depot for final delivery. LTL economics depend on hub volume. Connexx rate-shops across pallet networks for every B2B shipment.",
    related: "[Pallet network](#pallet-network), [FCL](#fcl--lcl-full--less-than-container-load), [/solutions/b2b](/solutions/b2b)",
  },
  {
    slug: "manifest",
    name: "Manifest",
    category: "Operational",
    definition: "The list of parcels in a single carrier collection, generated at the end of a dispatch session and presented to the driver.",
    context: "Each carrier requires a daily manifest. Royal Mail generates one through Click and Drop or its OBA system. DPD generates one through its portal. Multi-carrier platforms generate one manifest per carrier per collection automatically. A manifest is the source of truth for that day's volume.",
    related: "[Dispatch](#dispatch), [POD](#pod-proof-of-delivery)",
  },
  {
    slug: "pallet-network",
    name: "Pallet network",
    category: "Operational",
    definition: "A national or international network of haulage businesses that share a central hub to deliver palletised freight, allowing single-pallet shipments at competitive cost.",
    context: "Pall-Ex, Palletline, and Palletways are the dominant UK pallet networks. Each has 80 to 100 member depots across the UK. A shipper books once, the network handles collection, trunking, and delivery. Pallet sizes (quarter, half, full) and timed delivery windows are the main rate variables.",
    related: "[LTL](#ltl-less-than-truckload), [POD](#pod-proof-of-delivery), [/solutions/b2b](/solutions/b2b)",
  },
  {
    slug: "returns-logistics-reverse-logistics",
    name: "Returns logistics / reverse logistics",
    category: "Operational",
    definition: "The process of handling goods sent back from the customer, including return labels, carrier collection, warehouse receipt, and refund or restock decisions.",
    context: "Returns rates in UK eCommerce typically run 8 to 30 per cent depending on category. Returns logistics costs (label, freight, processing, restocking, write-off) can absorb 30 to 50 per cent of the gross margin on returned items. A returns portal that issues pre-paid labels through the right carrier per lane saves cost and reduces friction.",
    related: "[WISMO](#wismo-where-is-my-order), [Carrier portal](#carrier-portal), [/solutions/ecommerce](/solutions/ecommerce)",
  },
  {
    slug: "volumetric-weight",
    name: "Volumetric weight",
    category: "Operational",
    definition: "A synonym for dimensional weight, used by some carriers and freight forwarders to describe volume-based pricing.",
    context: "Volumetric weight and dimensional weight refer to the same calculation, with different divisors per carrier. Royal Mail does not apply volumetric weight on small parcels but DHL, FedEx, and UPS do on international.",
    related: "[Dimensional weight](#dimensional-weight-dim-weight), [Rate card](#rate-card)",
  },
  {
    slug: "wismo-where-is-my-order",
    name: "WISMO (Where Is My Order)",
    category: "Operational",
    definition: "The customer service ticket category covering \"where is my parcel?\" enquiries from customers waiting for a delivery.",
    context: "WISMO is the single largest CS ticket type for any UK eCommerce brand. At 80 tickets a day across four carriers, a CS team can spend five hours daily looking up tracking. The fix is a single tracking view inside the helpdesk, fed by the multi-carrier platform's tracking data. Peak Commerce cut WISMO tickets by 68 per cent on Connexx.",
    related: "[Tracking number](#tracking-number--consignment-reference), [CSAT](#csat), [/solutions/ecommerce](/solutions/ecommerce)\n\n---",
  },
  {
    slug: "api-application-programming-interface",
    name: "API (Application Programming Interface)",
    category: "Technical",
    definition: "A set of endpoints that lets one software system talk to another, used in shipping to connect order systems (Shopify, NetSuite) to carriers and platforms (Royal Mail, DPD, Connexx).",
    context: "Every modern carrier publishes an API. Every modern platform consumes them. A platform with native API connections beats one that uses CSV uploads, because the data flows in real time and writes back automatically. Connexx exposes its own REST API to customers who want to build custom workflows.",
    related: "[RESTful API](#restful-api), [Webhook](#webhook), [ERP write-back](#erp-write-back)",
  },
  {
    slug: "erp-write-back",
    name: "ERP write-back",
    category: "Technical",
    definition: "The process by which a shipping platform writes shipment data (tracking numbers, dispatch dates, costs, POD) back into the source ERP, so the order record is updated automatically.",
    context: "Without write-back, dispatch teams re-key tracking numbers into the ERP by hand. With write-back, the data flows. NetSuite and other major ERPs support write-back through API or middleware. Connexx supports two-way sync with every major ERP.",
    related: "[API](#api-application-programming-interface), [Webhook](#webhook), [Tracking number](#tracking-number--consignment-reference)",
  },
  {
    slug: "oms-order-management-system",
    name: "OMS (Order Management System)",
    category: "Technical",
    definition: "A software platform that aggregates orders from multiple sales channels (Shopify, Amazon, eBay, B2B portal) into one queue for dispatch.",
    context: "Linnworks, Veeqo, StoreFeeder, and Selro are the dominant UK OMS platforms for multi-channel sellers. The OMS holds the order until it is ready for dispatch. The shipping platform takes the dispatched order, picks the carrier, generates the label, and writes the tracking number back. Connexx integrates with every major OMS.",
    related: "[WMS](#wms-warehouse-management-system), [API](#api-application-programming-interface)",
  },
  {
    slug: "restful-api",
    name: "RESTful API",
    category: "Technical",
    definition: "A style of web API that uses standard HTTP methods (GET, POST, PUT, DELETE) and JSON payloads, the dominant pattern in modern software integration.",
    context: "A REST API is the easiest pattern to integrate against. Connexx's API is REST. Most modern carrier APIs are REST. Older carrier APIs use SOAP or proprietary XML, which Connexx handles internally so the customer never sees them.",
    related: "[API](#api-application-programming-interface), [Webhook](#webhook)",
  },
  {
    slug: "webhook",
    name: "Webhook",
    category: "Technical",
    definition: "An HTTP callback that one system sends to another when an event occurs (e.g. an order is created in Shopify, a parcel is scanned by DPD), enabling real-time data flow without polling.",
    context: "Webhooks are how shipping platforms get instant notification of order creation, dispatch, and delivery. Connexx receives Shopify order-created webhooks and pushes tracking events back via webhooks to the customer's ERP. Real-time webhook flow beats hourly batch polling for any time-sensitive workflow.",
    related: "[API](#api-application-programming-interface), [ERP write-back](#erp-write-back)",
  },
  {
    slug: "wms-warehouse-management-system",
    name: "WMS (Warehouse Management System)",
    category: "Technical",
    definition: "A software platform that manages warehouse operations including stock locations, picking, packing, and inventory accuracy.",
    context: "Mintsoft, ShipHero, Manhattan Active Warehouse, and Blue Yonder are the UK-relevant WMS platforms. A WMS controls what is on the shelf and where it goes. A shipping platform controls how it gets to the customer. The two systems integrate so an order picked in the WMS dispatches through the shipping platform automatically. Connexx integrates with every major WMS.",
    related: "[OMS](#oms-order-management-system), [API](#api-application-programming-interface), [/solutions/3pl](/solutions/3pl)\n\n---",
  },
  {
    slug: "customs-hold",
    name: "Customs hold",
    category: "Regulatory",
    definition: "A delay imposed by customs authorities (HMRC or the destination country's customs) on a shipment that fails initial checks, pending resolution of a documentation or compliance issue.",
    context: "Customs holds typically take 24 to 72 hours to resolve and require additional paperwork. The most common causes are misclassified HS codes, missing or wrong EORI, mismatched commercial invoice and packing list, and missing certificates. SwiftLog Fulfilment lifted customs accuracy from 93 per cent to 98.7 per cent on Connexx, cutting customs-related delays by 85 per cent.",
    related: "[Pre-clearance](#pre-clearance), [HS code](#hs-code-harmonised-system-code), [Commercial invoice](#commercial-invoice)",
  },
  {
    slug: "landed-cost",
    name: "Landed cost",
    category: "Regulatory",
    definition: "The total cost of getting goods from a supplier to the final destination, including supplier price, freight, insurance, duty, import VAT, customs fees, and any surcharges.",
    context: "Landed cost matters most for importers pricing products against margin. Estimates that are off by 10 to 20 per cent erode margin on every unit until the next price review. Northgate Imports lifted duty cost accuracy from 82 per cent to 97 per cent on Connexx, which let finance price every SKU against accurate margin.",
    related: "[Duty](#duty), [UK Global Tariff](#uk-global-tariff), [/solutions/import](/solutions/import)",
  },
  {
    slug: "surcharge-zone",
    name: "Surcharge zone",
    category: "Regulatory",
    definition: "A geographic area (typically postcodes) outside the carrier's standard delivery network, where the carrier applies an additional fee per shipment.",
    context: "Highlands, Islands, Channel Islands, Northern Ireland, and BFPO are the main UK surcharge zones. Each carrier has its own list. Routing rules in a multi-carrier platform pick the carrier with the lowest surcharge for the destination postcode.",
    related: "[Highlands & Islands](#highlands--islands), [Out-of-area](#out-of-area), [Mainland UK](#mainland-uk)",
  },
  {
    slug: "ipr-inward-processing-relief",
    name: "IPR (Inward Processing Relief)",
    category: "Regulatory",
    definition: "An HMRC scheme allowing UK importers to suspend or refund duty on goods imported for processing and re-export.",
    context: "IPR is for businesses that import components, process them in the UK, and export the finished product. Duty on the imported components is either suspended at import or refunded later. The paperwork burden is meaningful, which is why many eligible businesses do not use the scheme. Connexx tags IPR-eligible shipments for the claim.",
    related: "[Duty drawback](#duty-drawback), [OPR](#opr-outward-processing-relief)",
  },
  {
    slug: "opr-outward-processing-relief",
    name: "OPR (Outward Processing Relief)",
    category: "Regulatory",
    definition: "An HMRC scheme allowing UK exporters to send goods abroad for processing and re-import them with duty calculated only on the value added abroad, not the full re-import value.",
    context: "OPR is the export counterpart to IPR. Used by businesses that send raw materials or components abroad for finishing and then re-import. Common in fashion, electronics assembly, and machinery. Connexx flags OPR-eligible movements and tracks them through the re-import.",
    related: "[IPR](#ipr-inward-processing-relief), [Duty](#duty)\n\n---",
  },
];

export const GLOSSARY_CATEGORIES: { id: GlossaryCategory; label: string; description: string }[] = [
  { id: 'Carrier', label: 'Carrier terms', description: 'How UK and international carriers price, dispatch, and deliver.' },
  { id: 'Customs', label: 'Customs and trade', description: 'Documentation, classification, and clearance terms for UK and international trade.' },
  { id: 'Operational', label: 'Operational', description: 'Vocabulary used in dispatch teams, warehouses, and customer service.' },
  { id: 'Technical', label: 'Technical', description: 'API, integration, and platform vocabulary.' },
  { id: 'Regulatory', label: 'Regulatory and zones', description: 'Regulators, surcharge zones, and geographies that shape UK shipping.' },
];
