// Glossary data — single source of truth for /resources/glossary.
// Generated from the canonical Google Sheet (Category, Term, Tag, Anchor Slug,
// Definition, Context, Related Terms, Related Product Links). Anchor slugs are
// taken verbatim from the sheet (several differ from naive slugification).

export type Category =
  | "Carrier"
  | "Customs"
  | "Operational"
  | "Technical"
  | "Regulatory";

export type RelatedLink = {
  label: string;
  href: string;
};

export type Entry = {
  slug: string;
  code?: string;
  name: string;
  category: Category;
  definition: string;
  context: string;
  related: RelatedLink[];
};

export const categories: { key: Category; label: string; description: string }[] = [
  {
    key: "Carrier",
    label: "Carrier",
    description: "Carrier services, portals, and metrics that shape the dispatch workflow.",
  },
  {
    key: "Customs",
    label: "Customs",
    description: "Declarations, certificates, and trade terms for cross-border movement.",
  },
  {
    key: "Operational",
    label: "Operational",
    description: "The day-to-day language of dispatch, freight, and warehouse operations.",
  },
  {
    key: "Technical",
    label: "Technical",
    description: "APIs, systems, and the connections that move data between platforms.",
  },
  {
    key: "Regulatory",
    label: "Regulatory",
    description: "HMRC schemes, customs zones, and the rules that drive landed cost.",
  },
];

export const GLOSSARY_ENTRIES: Entry[] = [
  {
    slug: "buy-shipping-amazon",
    name: "Buy Shipping (Amazon)",
    category: "Carrier",
    definition: "Amazon's discounted shipping rates available only for orders placed on Amazon, bought through Seller Central or an integrated platform.",
    context: "Amazon Buy Shipping covers a limited carrier list (Royal Mail, Amazon Shipping, Evri, and a handful of others) at negotiated rates. It is cheap for Amazon orders and useless for everything else. Sellers running Amazon plus eBay, Etsy, or Shopify need a multi-carrier platform that includes Amazon Buy Shipping inside a wider queue.",
    related: [
      { label: "Seller Fulfilled Prime", href: "#seller-fulfilled-prime-sfp" },
      { label: "Valid Tracking Rate", href: "#valid-tracking-rate-vtr" },
      { label: "Marketplace seller solution", href: "/solutions/marketplace-seller" },
    ],
  },
  {
    slug: "carrier-portal",
    name: "Carrier portal",
    category: "Carrier",
    definition: "The website a carrier provides for booking shipments, printing labels, and tracking parcels for a single account.",
    context: "Every UK shipper recognises the pattern. Royal Mail Click and Drop, DPD Shipping Portal, Evri Business, DHL MyDHL+, Amazon Seller Central. A business shipping through four carriers logs into four portals. Multi-carrier platforms replace the portal stack with one queue.",
    related: [
      { label: "Multi-carrier", href: "#multi-carrier" },
      { label: "Rate engine", href: "#rate-engine" },
      { label: "Connexx", href: "/connexx" },
    ],
  },
  {
    slug: "child-account",
    name: "Child account",
    category: "Carrier",
    definition: "A sub-account under a parent carrier contract, typically used by 3PLs to give each brand client its own rate card, reporting, and labels.",
    context: "A 3PL holds the master agreement with Royal Mail, DPD, Evri, or DHL and creates a child account per brand client. Each child account has its own rate card, its own dispatch rules, and its own branded tracking page. Connexx manages unlimited child accounts under one parent contract, with billing and SLAs tracked per client.",
    related: [
      { label: "Multi-carrier", href: "#multi-carrier" },
      { label: "Rate card", href: "#rate-card" },
      { label: "3PL solution", href: "/solutions/3pl" },
    ],
  },
  {
    slug: "click-and-drop-royal-mail",
    name: "Click and Drop (Royal Mail)",
    category: "Carrier",
    definition: "Royal Mail's free online shipping tool for printing labels and booking collections.",
    context: "Click and Drop is the default starting point for UK small businesses on Royal Mail. It works for Royal Mail-only operations. Once a business adds Evri, DPD, or Parcelforce, the workflow fragments and the team starts juggling portals.",
    related: [
      { label: "Carrier portal", href: "#carrier-portal" },
      { label: "Multi-carrier", href: "#multi-carrier" },
      { label: "Royal Mail Tracked 24/48", href: "#royal-mail-tracked-2448" },
    ],
  },
  {
    slug: "drop-off-parcelshop-locker",
    name: "Drop-off (ParcelShop, locker)",
    category: "Carrier",
    definition: "A delivery option where the parcel is dropped at a third-party location (shop or locker) rather than collected from the sender or delivered to a residence.",
    context: "Evri ParcelShop, InPost lockers, and Royal Mail Customer Service Points are the main UK drop-off networks. Drop-off rates are typically 30 to 40 per cent cheaper than door collection. Most consumer eCommerce brands offer drop-off as a low-cost delivery tier at checkout.",
    related: [
      { label: "Out-of-area", href: "#out-of-area" },
      { label: "Surcharge zone", href: "#surcharge-zone" },
    ],
  },
  {
    slug: "fuel-surcharge",
    name: "Fuel surcharge",
    category: "Carrier",
    definition: "A variable cost line every carrier adds to base shipping rates to cover diesel and aviation fuel price movement.",
    context: "Royal Mail, DPD, DHL, FedEx, UPS, and the pallet networks all publish a monthly fuel surcharge as a percentage of the base rate. It changes month to month. Carrier portals show it in the invoice. A rate engine has to pull the live surcharge to compare carriers honestly.",
    related: [
      { label: "Rate card", href: "#rate-card" },
      { label: "Negotiated rate", href: "#negotiated-rate" },
      { label: "Surcharge zone", href: "#surcharge-zone" },
    ],
  },
  {
    slug: "highlands--islands",
    name: "Highlands & Islands",
    category: "Carrier",
    definition: "The UK surcharge zone covering the Scottish Highlands, Scottish islands, Isle of Man, and the Channel Islands, where every major carrier applies an additional fee.",
    context: "Every UK shipper knows the Highlands surcharge. A parcel from London to Inverness costs more than London to Glasgow on most carriers. The postcode prefixes that trigger the surcharge are published by each carrier and change occasionally. Routing rules in a multi-carrier platform apply the right carrier per postcode automatically.",
    related: [
      { label: "Out-of-area", href: "#out-of-area" },
      { label: "Surcharge zone", href: "#surcharge-zone" },
      { label: "Mainland UK", href: "#mainland-uk" },
    ],
  },
  {
    slug: "late-shipment-rate-lsr",
    code: "LSR",
    name: "Late Shipment Rate (LSR)",
    category: "Carrier",
    definition: "An Amazon and eBay seller metric tracking the percentage of orders dispatched after the platform's deadline.",
    context: "Amazon's LSR threshold is 4 per cent. Cross it and your seller account is at risk of suspension. The metric is unforgiving because it covers every order shipped from your seller account, including orders missed during a system outage or a carrier strike.",
    related: [
      { label: "Valid Tracking Rate", href: "#valid-tracking-rate-vtr" },
      { label: "On-Time Delivery Rate", href: "#on-time-delivery-rate-otdr" },
      { label: "Marketplace seller solution", href: "/solutions/marketplace-seller" },
    ],
  },
  {
    slug: "mainland-uk",
    name: "Mainland UK",
    category: "Carrier",
    definition: "The carrier zone covering England, Wales, and mainland Scotland, excluding the Highlands, Islands, Channel Islands, and Northern Ireland.",
    context: "Mainland UK is the base zone. Highlands & Islands, Channel Islands, Northern Ireland, and BFPO addresses each carry surcharges or different routing. Carrier rate cards quote a Mainland UK price and then list the surcharge zones separately.",
    related: [
      { label: "Highlands & Islands", href: "#highlands--islands" },
      { label: "Out-of-area", href: "#out-of-area" },
      { label: "Surcharge zone", href: "#surcharge-zone" },
    ],
  },
  {
    slug: "multi-carrier",
    name: "Multi-carrier",
    category: "Carrier",
    definition: "A shipping setup that connects one business to two or more parcel carriers from a single platform, with rate comparison between them per order.",
    context: "The product category Connexx belongs to. A multi-carrier platform compares live rates across Royal Mail, DPD, Evri, Parcelforce, DHL, FedEx, UPS, Amazon Shipping, and others on every shipment, picks the cheapest compliant option, and generates the label in one click. The alternative is logging into each carrier's portal separately.",
    related: [
      { label: "Rate engine", href: "#rate-engine" },
      { label: "Negotiated rate", href: "#negotiated-rate" },
      { label: "Connexx", href: "/connexx" },
    ],
  },
  {
    slug: "negotiated-rate",
    name: "Negotiated rate",
    category: "Carrier",
    definition: "A carrier rate lower than the published rack rate, available to high-volume shippers or to platforms that aggregate volume across many customers.",
    context: "Royal Mail, DPD, Evri, and DHL all negotiate rates against committed volume. A small business shipping 50 parcels a day will not get a negotiated rate directly. A platform like Connexx aggregates volume across thousands of shippers and passes the negotiated rates down to every customer, regardless of individual volume.",
    related: [
      { label: "Rack rate", href: "#rack-rate" },
      { label: "Rate card", href: "#rate-card" },
      { label: "Multi-carrier", href: "#multi-carrier" },
    ],
  },
  {
    slug: "on-time-delivery-rate-otdr",
    code: "OTDR",
    name: "On-Time Delivery Rate (OTDR)",
    category: "Carrier",
    definition: "An Amazon seller metric tracking the percentage of orders delivered by the promised delivery date.",
    context: "OTDR is Amazon's newer SLA metric, complementing Valid Tracking Rate and Late Shipment Rate. The threshold is 92 per cent. Carrier choice, dispatch cutoff, and weather all affect it. A multi-carrier platform routes Amazon orders through carriers with strong OTDR performance on the specific lane and weight tier.",
    related: [
      { label: "Valid Tracking Rate", href: "#valid-tracking-rate-vtr" },
      { label: "Late Shipment Rate", href: "#late-shipment-rate-lsr" },
      { label: "Marketplace seller solution", href: "/solutions/marketplace-seller" },
    ],
  },
  {
    slug: "out-of-area",
    name: "Out-of-area",
    category: "Carrier",
    definition: "A postcode outside a carrier's standard delivery zone, where the carrier applies a surcharge or refuses the shipment.",
    context: "Every UK carrier publishes an out-of-area postcode list. Highlands, Islands, Channel Islands, and Northern Ireland are the common ones. DPD and Evri each have slightly different lists, which is why an automated routing rule beats a manual choice. A wrong out-of-area decision costs a redelivery charge or a returned parcel.",
    related: [
      { label: "Highlands & Islands", href: "#highlands--islands" },
      { label: "Surcharge zone", href: "#surcharge-zone" },
      { label: "Mainland UK", href: "#mainland-uk" },
    ],
  },
  {
    slug: "pod-proof-of-delivery",
    code: "POD",
    name: "POD (Proof of Delivery)",
    category: "Carrier",
    definition: "Evidence that a parcel was delivered, usually a signature or photograph captured by the carrier driver at the delivery address.",
    context: "B2B shipments depend on POD because the buyer expects evidence the consignment arrived intact. DPD, DHL, UPS, and the pallet networks all capture signature or photo POD by default. Connexx pulls POD events back into the ERP automatically so finance and customer service can answer disputes without logging into a carrier portal.",
    related: [
      { label: "SLA", href: "#sla-service-level-agreement" },
      { label: "Tracking number / consignment reference", href: "#tracking-number--consignment-reference" },
      { label: "B2B solution", href: "/solutions/b2b" },
    ],
  },
  {
    slug: "rack-rate",
    name: "Rack rate",
    category: "Carrier",
    definition: "A carrier's published list price for a shipment, before any negotiated discount.",
    context: "Rack rates are the rates a small or new shipper pays unless they negotiate. Royal Mail publishes Business Account rack rates. DPD publishes a public rate card. Volume buyers and aggregator platforms negotiate below rack. The gap between rack and negotiated is where Connexx saves money for small and mid-market shippers.",
    related: [
      { label: "Negotiated rate", href: "#negotiated-rate" },
      { label: "Rate card", href: "#rate-card" },
    ],
  },
  {
    slug: "rate-card",
    name: "Rate card",
    category: "Carrier",
    definition: "The price schedule for a carrier's services, broken down by weight tier, destination zone, and service speed.",
    context: "Every carrier has a rate card. Royal Mail's is structured by service (Tracked 24, Tracked 48, Special Delivery), weight band, and destination. DPD's adds size-based dim weight. A 3PL holds a rate card per client. Rate cards change at least annually and often quarterly.",
    related: [
      { label: "Rack rate", href: "#rack-rate" },
      { label: "Negotiated rate", href: "#negotiated-rate" },
      { label: "Rate engine", href: "#rate-engine" },
    ],
  },
  {
    slug: "rate-engine",
    name: "Rate engine",
    category: "Carrier",
    definition: "The component of a shipping platform that compares carrier rates in real time on every shipment and picks the optimal carrier against pre-set rules.",
    context: "A rate engine takes a shipment (weight, dimensions, destination, service required) and runs it against every active carrier's rate card and routing logic. Connexx's rate engine evaluates every carrier on every order in under 200 milliseconds. The output is a ranked list of compliant carriers with their cost and SLA.",
    related: [
      { label: "Multi-carrier", href: "#multi-carrier" },
      { label: "Rate card", href: "#rate-card" },
      { label: "Connexx", href: "/connexx" },
    ],
  },
  {
    slug: "royal-mail-tracked-2448",
    name: "Royal Mail Tracked 24/48",
    category: "Carrier",
    definition: "Royal Mail's tracked parcel services, with target delivery in one working day (Tracked 24) or two working days (Tracked 48).",
    context: "Tracked 24 and Tracked 48 are the workhorses of UK eCommerce. They cover every UK postcode, push scan events back to Amazon and other marketplaces within the SLA, and qualify for Amazon Seller Fulfilled Prime. Most UK retailers ship sub-2kg orders on Tracked 48 by default.",
    related: [
      { label: "Buy Shipping", href: "#buy-shipping-amazon" },
      { label: "Seller Fulfilled Prime", href: "#seller-fulfilled-prime-sfp" },
      { label: "Valid Tracking Rate", href: "#valid-tracking-rate-vtr" },
    ],
  },
  {
    slug: "saturday-delivery",
    name: "Saturday delivery",
    category: "Carrier",
    definition: "A delivery service that operates on Saturdays, usually carrying an additional surcharge above weekday rates.",
    context: "DPD Saturday, Parcelforce Saturday, and Royal Mail Special Delivery all offer Saturday delivery. The surcharge is meaningful (typically \u00a33 to \u00a37 above the weekday rate). Multi-carrier platforms apply Saturday routing only when the customer paid for it at checkout, not by default.",
    related: [
      { label: "SLA", href: "#sla-service-level-agreement" },
      { label: "Rate card", href: "#rate-card" },
    ],
  },
  {
    slug: "seller-fulfilled-prime-sfp",
    code: "SFP",
    name: "Seller Fulfilled Prime (SFP)",
    category: "Carrier",
    definition: "An Amazon programme that lets sellers offer Prime two-day delivery from their own warehouse, instead of Amazon FBA, using Amazon-approved carriers.",
    context: "SFP requires sellers to meet strict performance thresholds (Valid Tracking Rate, Late Shipment Rate, On-Time Delivery Rate) and ship through approved carriers (Royal Mail Tracked 24, Amazon Shipping, DPD Next Day, and a small list of others). Sellers running SFP need carrier routing that defaults to the approved list and falls back gracefully when an order does not meet the criteria.",
    related: [
      { label: "Buy Shipping", href: "#buy-shipping-amazon" },
      { label: "Valid Tracking Rate", href: "#valid-tracking-rate-vtr" },
      { label: "Marketplace seller solution", href: "/solutions/marketplace-seller" },
    ],
  },
  {
    slug: "sla-service-level-agreement",
    code: "SLA",
    name: "SLA (Service Level Agreement)",
    category: "Carrier",
    definition: "The carrier's contractual delivery promise, typically expressed as a target delivery time (e.g. next working day before 12pm) and a percentage of shipments delivered within it.",
    context: "SLAs vary by service, by destination, and by carrier. DPD Next Day Before 12 is a different SLA from DPD Next Day. Carrier SLA data feeds into a multi-carrier platform's routing logic and into the customer-facing delivery promise at checkout. Missed SLAs are the source of most customer service tickets.",
    related: [
      { label: "POD", href: "#pod-proof-of-delivery" },
      { label: "WISMO", href: "#wismo-where-is-my-order" },
      { label: "Late Shipment Rate", href: "#late-shipment-rate-lsr" },
    ],
  },
  {
    slug: "tracking-number--consignment-reference",
    name: "Tracking number / consignment reference",
    category: "Carrier",
    definition: "The unique identifier the carrier assigns to a parcel or consignment, used to look up its status at any point in the journey.",
    context: "Royal Mail uses a 13-character reference. DPD uses a 14-digit number. UPS uses 1Z followed by 16 characters. Each carrier's format is different. Connexx normalises tracking numbers into a single field per order and writes them back to Shopify, Amazon, eBay, or your ERP automatically.",
    related: [
      { label: "POD", href: "#pod-proof-of-delivery" },
      { label: "WISMO", href: "#wismo-where-is-my-order" },
      { label: "ERP write-back", href: "#erp-write-back" },
    ],
  },
  {
    slug: "valid-tracking-rate-vtr",
    code: "VTR",
    name: "Valid Tracking Rate (VTR)",
    category: "Carrier",
    definition: "An Amazon seller metric tracking the percentage of orders dispatched with a valid tracking number that scans within the SLA window.",
    context: "Amazon's VTR threshold is 95 per cent. Carriers that scan parcels on collection (Royal Mail Tracked 24/48, Amazon Shipping, DPD) meet VTR cleanly. Non-tracked services do not. Connexx routes Amazon orders through VTR-compliant carriers by default and writes the tracking number back to Seller Central before the dispatch deadline.",
    related: [
      { label: "Late Shipment Rate", href: "#late-shipment-rate-lsr" },
      { label: "On-Time Delivery Rate", href: "#on-time-delivery-rate-otdr" },
      { label: "Seller Fulfilled Prime", href: "#seller-fulfilled-prime-sfp" },
      { label: "Marketplace seller solution", href: "/solutions/marketplace-seller" },
    ],
  },
  {
    slug: "collection-cutoff",
    name: "Collection cutoff",
    category: "Carrier",
    definition: "The time each day by which a parcel must be prepared and handed to the carrier to qualify for that day's collection.",
    context: "Miss the collection cutoff and the parcel ships the next working day, which can push a next-day delivery to day three. Cutoffs vary by carrier and service: DPD's is typically 5pm, Royal Mail OBA 5:30pm, but both depend on account configuration. Connexx tracks cutoffs per carrier and flags orders at risk of missing the same-day window.",
    related: [
      { label: "Dispatch", href: "#dispatch" },
      { label: "Late Shipment Rate", href: "#late-shipment-rate-lsr" },
      { label: "SLA", href: "#sla-service-level-agreement" },
      { label: "Connexx", href: "/connexx" },
    ],
  },
  {
    slug: "consignment",
    name: "Consignment",
    category: "Carrier",
    definition: "A shipment or batch of goods sent from one sender to one recipient under a single set of carrier documentation.",
    context: "In parcel shipping, a consignment is usually a single parcel. In freight, it covers multiple items or pallets moving together under one consignment note. The consignment reference is what the carrier, the ERP, and customs track against. Connexx generates a unique consignment reference per booking and writes it back to the originating order.",
    related: [
      { label: "Tracking number / consignment reference", href: "#tracking-number--consignment-reference" },
      { label: "Manifest", href: "#manifest" },
      { label: "POD", href: "#pod-proof-of-delivery" },
    ],
  },
  {
    slug: "delivery-exception",
    name: "Delivery exception",
    category: "Carrier",
    definition: "Any event that prevents a parcel reaching its destination on the scheduled delivery day, such as an incorrect address, a failed delivery attempt, or a damaged item.",
    context: "Delivery exceptions are the primary driver of WISMO tickets and customer complaints. Common causes are incorrect address data, recipient not available, access restrictions, and damaged packaging. A multi-carrier platform surfaces exception events in real time so the customer service team can intervene before the customer calls.",
    related: [
      { label: "WISMO", href: "#wismo-where-is-my-order" },
      { label: "CSAT", href: "#csat" },
      { label: "Tracking number / consignment reference", href: "#tracking-number--consignment-reference" },
      { label: "eCommerce solution", href: "/solutions/ecommerce" },
    ],
  },
  {
    slug: "evri",
    name: "Evri",
    category: "Carrier",
    definition: "A UK parcel carrier (formerly Hermes) operating one of the largest drop-off and door-to-door delivery networks in the country, used predominantly for B2C eCommerce.",
    context: "Evri handles over 700 million parcels a year through a combination of courier delivery, ParcelShop drop-off points, and lockers. Its rates are among the lowest in the UK market, making it a default choice for high-volume B2C shippers on non-premium services. Connexx integrates Evri alongside Royal Mail, DPD, and others in a single rate comparison.",
    related: [
      { label: "Multi-carrier", href: "#multi-carrier" },
      { label: "Drop-off", href: "#drop-off-parcelshop-locker" },
      { label: "Rate engine", href: "#rate-engine" },
      { label: "eCommerce solution", href: "/solutions/ecommerce" },
    ],
  },
  {
    slug: "parcelforce-worldwide",
    name: "Parcelforce Worldwide",
    category: "Carrier",
    definition: "Royal Mail Group's express parcel carrier, operating UK next-day, 48-hour, and international tracked services for business shippers.",
    context: "Parcelforce operates its own depot network and fleet, separate from Royal Mail's letter and packet network. It is a common choice for heavier domestic parcels (above 2kg) and international tracked shipments where Royal Mail International Tracked does not offer the right SLA. Connexx integrates Parcelforce alongside Royal Mail and other carriers in a single booking queue.",
    related: [
      { label: "Royal Mail Tracked 24/48", href: "#royal-mail-tracked-2448" },
      { label: "Multi-carrier", href: "#multi-carrier" },
      { label: "Rate card", href: "#rate-card" },
      { label: "Connexx", href: "/connexx" },
    ],
  },
  {
    slug: "special-delivery-guaranteed",
    name: "Special Delivery Guaranteed (Royal Mail)",
    category: "Carrier",
    definition: "Royal Mail's guaranteed next-day delivery service with a time-certain delivery promise (by 1pm or 9am) and automatic compensation for loss or damage.",
    context: "Special Delivery is the premium domestic Royal Mail service, used for high-value, time-sensitive, or legally important items. It includes up to \u00a3750 of compensation as standard, with enhancement available. Most businesses use it only for specific SKU categories (jewellery, documents, electronics) because the cost per parcel is significantly above Tracked 24.",
    related: [
      { label: "Royal Mail Tracked 24/48", href: "#royal-mail-tracked-2448" },
      { label: "SLA", href: "#sla-service-level-agreement" },
      { label: "Rate card", href: "#rate-card" },
    ],
  },
  {
    slug: "amazon-shipping",
    name: "Amazon Shipping",
    category: "Carrier",
    definition: "Amazon's own UK parcel carrier network, available to sellers using Seller Central or integrated platforms, operating alongside external carriers like Royal Mail and DPD.",
    context: "Amazon Shipping is distinct from FBA: the seller ships from their own warehouse, but Amazon's drivers collect and deliver. It qualifies for Amazon Buy Shipping discounts and satisfies VTR and OTDR thresholds automatically. Coverage is Mainland UK with a growing footprint. Connexx includes Amazon Shipping in the rate engine so it competes on every order against Royal Mail, Evri, and DPD.",
    related: [
      { label: "Buy Shipping", href: "#buy-shipping-amazon" },
      { label: "Valid Tracking Rate", href: "#valid-tracking-rate-vtr" },
      { label: "Seller Fulfilled Prime", href: "#seller-fulfilled-prime-sfp" },
      { label: "Marketplace seller solution", href: "/solutions/marketplace-seller" },
    ],
  },
  {
    slug: "bfpo-british-forces-post-office",
    code: "BFPO",
    name: "BFPO (British Forces Post Office)",
    category: "Carrier",
    definition: "The delivery zone covering British military bases and armed forces addresses worldwide, treated by UK carriers as a separate service with its own postcode prefix (BF1) and routing rules.",
    context: "BFPO addresses appear alongside Highlands & Islands, Channel Islands, and Northern Ireland in carrier coverage maps. Royal Mail serves BFPO addresses at standard domestic rates. Most other carriers apply a surcharge or decline the service altogether. Multi-carrier routing rules should explicitly assign the right carrier per BFPO postcode rather than defaulting to the standard domestic logic.",
    related: [
      { label: "Highlands & Islands", href: "#highlands--islands" },
      { label: "Out-of-area", href: "#out-of-area" },
      { label: "Surcharge zone", href: "#surcharge-zone" },
    ],
  },
  {
    slug: "dpd-predict",
    name: "DPD Predict",
    category: "Carrier",
    definition: "DPD's real-time delivery notification service that gives the recipient a confirmed one-hour delivery window on the morning of delivery, along with live driver tracking.",
    context: "DPD Predict is the standard notification for DPD Next Day shipments. The customer receives a text or email with their one-hour slot, a map of the driver's progress, and options to change the delivery. It is the most granular pre-delivery communication of any UK carrier, which is why DPD scores consistently higher on consumer delivery satisfaction surveys. Connexx enables DPD Predict automatically on every DPD shipment.",
    related: [
      { label: "SLA", href: "#sla-service-level-agreement" },
      { label: "CSAT", href: "#csat" },
      { label: "Tracking event", href: "#tracking-event" },
      { label: "eCommerce solution", href: "/solutions/ecommerce" },
    ],
  },
  {
    slug: "dx",
    name: "DX",
    category: "Carrier",
    definition: "A UK B2B specialist carrier handling irregular dimensions, heavy items, and two-man delivery, primarily serving business-to-business and enterprise accounts.",
    context: "DX operates where standard parcel carriers struggle: oversized parcels, items that need two people to deliver, and business postcodes where residential network coverage is weak. It sits alongside DPD and Parcelforce in the rate engine for B2B consignments that fall outside standard weight and dimension rules. Connexx routes to DX automatically when the shipment specs or delivery requirements exceed the standard carrier thresholds.",
    related: [
      { label: "LTL", href: "#ltl-less-than-truckload" },
      { label: "POD", href: "#pod-proof-of-delivery" },
      { label: "Rate engine", href: "#rate-engine" },
      { label: "B2B solution", href: "/solutions/b2b" },
    ],
  },
  {
    slug: "inpost",
    name: "InPost",
    category: "Carrier",
    definition: "A parcel carrier and locker network operating across UK residential areas, offering next-day, 48-hour, and Sunday delivery with a strong focus on B2C eCommerce.",
    context: "InPost operates over 4,000 locker locations across the UK, predominantly in supermarket and retail car parks. It is a cost-competitive option for residential eCommerce deliveries and one of the few carriers offering Sunday delivery at scale. Connexx integrates InPost alongside Royal Mail, DPD, and Evri so locker delivery competes in the rate engine for every eligible order.",
    related: [
      { label: "Drop-off", href: "#drop-off-parcelshop-locker" },
      { label: "Click and Collect", href: "#click-and-collect" },
      { label: "Rate engine", href: "#rate-engine" },
      { label: "eCommerce solution", href: "/solutions/ecommerce" },
    ],
  },
  {
    slug: "postnl",
    name: "PostNL",
    category: "Carrier",
    definition: "The Dutch national postal operator and one of Europe's largest parcel networks, used by UK exporters for cost-effective B2C parcel delivery to EU destinations.",
    context: "PostNL is a strong choice for low-value B2C parcels to the Netherlands, Belgium, and broader EU markets where express speed is not the primary requirement. It handles IOSS-registered shipments and supports the EU's postal customs requirements. PostNL is not a premium express carrier \u2014 transit times run 3 to 7 days \u2014 but it is significantly cheaper than DHL or FedEx on low-value consumer goods going to EU postal addresses.",
    related: [
      { label: "IOSS", href: "#ioss-import-one-stop-shop" },
      { label: "DDP", href: "#ddp-delivered-duty-paid" },
      { label: "Rate engine", href: "#rate-engine" },
      { label: "Export solution", href: "/solutions/export" },
    ],
  },
  {
    slug: "residential-surcharge",
    name: "Residential surcharge",
    category: "Carrier",
    definition: "An additional fee some carriers apply to deliveries to residential addresses, reflecting the higher cost of delivering to homes compared to business premises.",
    context: "Residential surcharges are common on pallet network and freight carrier invoices and are beginning to appear on express parcel carrier rate cards. A B2B shipper sending to a domestic address (e.g. a home office buyer) can be caught by a residential levy not visible in the base rate. Connexx builds residential surcharge logic into the rate engine so the cost displayed at booking reflects the actual charge on the invoice.",
    related: [
      { label: "Surcharge zone", href: "#surcharge-zone" },
      { label: "Rate card", href: "#rate-card" },
      { label: "Fuel surcharge", href: "#fuel-surcharge" },
    ],
  },
  {
    slug: "ata-carnet",
    name: "ATA Carnet",
    category: "Customs",
    definition: "An international customs document that allows temporary import of goods (samples, professional equipment, exhibition stock) into a country without paying duty.",
    context: "ATA Carnets are issued by chambers of commerce in the goods' home country. UK exporters use them for trade shows, demo equipment, and broadcast kit. The carnet has a one-year validity and is presented at customs in both directions. Connexx flags carnet-eligible shipments at the point of booking.",
    related: [
      { label: "CDS", href: "#cds-customs-declaration-service" },
      { label: "HS code", href: "#hs-code-harmonised-system-code" },
    ],
  },
  {
    slug: "atr-movement-certificate-eu-turkey",
    name: "ATR (movement certificate, EU-Turkey)",
    category: "Customs",
    definition: "A movement certificate proving that goods qualify for preferential customs treatment under the EU-Turkey Customs Union.",
    context: "An ATR is required for shipments between the EU and Turkey to benefit from zero or reduced duty. Without it, standard tariffs apply. UK exporters to Turkey now need an ATR plus a UK-Turkey trade agreement document depending on the goods category. Connexx generates ATRs automatically for Turkey-bound shipments.",
    related: [
      { label: "EUR.1", href: "#eur1-movement-certificate" },
      { label: "Rules of origin", href: "#rules-of-origin" },
      { label: "Export solution", href: "/solutions/export" },
    ],
  },
  {
    slug: "c79-vat-certificate",
    code: "C79",
    name: "C79 (VAT certificate)",
    category: "Customs",
    definition: "A monthly certificate from HMRC showing the import VAT a UK business has paid through CHIEF or CDS, used to reclaim VAT on the next return.",
    context: "Importers using Postponed VAT Accounting receive a C79 from HMRC each month. The figure has to be reconciled against accounting records before submitting the VAT return. Connexx reconciles the C79 against shipment-level import VAT data automatically and exports the result to the finance system.",
    related: [
      { label: "PVA", href: "#pva-postponed-vat-accounting" },
      { label: "Duty deferment", href: "#duty-deferment" },
      { label: "Import solution", href: "/solutions/import" },
    ],
  },
  {
    slug: "cds-customs-declaration-service",
    code: "CDS",
    name: "CDS (Customs Declaration Service)",
    category: "Customs",
    definition: "HMRC's customs declaration platform, used by UK importers, exporters, and customs brokers to submit declarations to UK customs.",
    context: "CDS replaced CHIEF in 2023 for imports and 2024 for exports. Every UK customs declaration now flows through CDS, either submitted directly by the trader or filed by a customs broker on their behalf. Connexx connects to CDS through certified intermediaries and submits declarations before goods arrive at the port.",
    related: [
      { label: "CHIEF", href: "#chief-legacy-uk-customs-system" },
      { label: "Pre-clearance", href: "#pre-clearance" },
      { label: "EORI", href: "#eori-economic-operators-registration-and-identification" },
      { label: "Import solution", href: "/solutions/import" },
    ],
  },
  {
    slug: "certificate-of-origin",
    name: "Certificate of origin",
    category: "Customs",
    definition: "A document declaring the country where goods were produced, required by certain importing countries for customs clearance or to qualify for preferential duty.",
    context: "Certificates of origin are issued by chambers of commerce or generated from the trader's own records. Some destinations (Saudi Arabia, Egypt, India, several African markets) require chamber-issued certificates. Others accept self-certification. Connexx generates the correct document type per destination automatically.",
    related: [
      { label: "EUR.1", href: "#eur1-movement-certificate" },
      { label: "Rules of origin", href: "#rules-of-origin" },
      { label: "Commercial invoice", href: "#commercial-invoice" },
    ],
  },
  {
    slug: "chief-legacy-uk-customs-system",
    code: "CHIEF",
    name: "CHIEF (legacy UK customs system)",
    category: "Customs",
    definition: "HMRC's previous customs declaration platform, replaced by CDS for imports in 2023 and exports in 2024.",
    context: "CHIEF was the UK customs backbone for decades. CDS replaced it in stages. Any software stack that has not migrated from CHIEF to CDS is out of date. Connexx submits declarations through CDS from day one.",
    related: [
      { label: "CDS", href: "#cds-customs-declaration-service" },
      { label: "HMRC", href: "#hmrc" },
      { label: "Pre-clearance", href: "#pre-clearance" },
    ],
  },
  {
    slug: "commercial-invoice",
    name: "Commercial invoice",
    category: "Customs",
    definition: "The document showing the commercial value of an international shipment, used by customs to assess duty and VAT.",
    context: "Every international shipment needs a commercial invoice. It lists the goods, the HS code, the unit value, the seller, the buyer, the EORI numbers, and the Incoterms. A wrong line on the commercial invoice triggers a customs hold. Connexx generates commercial invoices from the sales order data automatically so the figures match across the documentation pack.",
    related: [
      { label: "Packing list", href: "#packing-list" },
      { label: "HS code", href: "#hs-code-harmonised-system-code" },
      { label: "EORI", href: "#eori-economic-operators-registration-and-identification" },
    ],
  },
  {
    slug: "ddp-delivered-duty-paid",
    code: "DDP",
    name: "DDP (Delivered Duty Paid)",
    category: "Customs",
    definition: "An Incoterm where the seller pays the duty and import VAT, and the goods arrive at the buyer with no customs charges to pay on delivery.",
    context: "DDP is the eCommerce-friendly Incoterm for cross-border B2C. The customer sees the final landed price at checkout and the parcel arrives with no surprises. DDP requires the seller to know the duty rate, calculate it at checkout, and pass it to the carrier. DHL Express, DPD Cross-Border, and a handful of others support DDP at the parcel level.",
    related: [
      { label: "Incoterms", href: "#incoterms" },
      { label: "DDU", href: "#ddu-delivered-duty-unpaid" },
      { label: "Landed cost", href: "#landed-cost" },
    ],
  },
  {
    slug: "ddu-delivered-duty-unpaid",
    code: "DDU",
    name: "DDU (Delivered Duty Unpaid)",
    category: "Customs",
    definition: "An Incoterm where the seller delivers goods to the buyer's country but the buyer pays import duty and VAT on arrival.",
    context: "DDU is the cheapest Incoterm for the seller and the worst for the customer. The customer gets an unexpected bill on the doorstep. For B2C cross-border, DDU drives complaints and refused deliveries. Most carriers no longer use the term DDU, having moved to DAP (Delivered at Place) under Incoterms 2020, but the legacy term is still common.",
    related: [
      { label: "DDP", href: "#ddp-delivered-duty-paid" },
      { label: "Incoterms", href: "#incoterms" },
      { label: "Landed cost", href: "#landed-cost" },
    ],
  },
  {
    slug: "duty",
    name: "Duty",
    category: "Customs",
    definition: "A tax charged by a country on imported goods, calculated as a percentage of the goods' customs value (usually the commercial invoice value plus freight and insurance).",
    context: "Duty rates depend on the HS code and the country of origin. The UK Global Tariff publishes UK import duty rates. EU duty rates are published in the EU's TARIC database. Duty is paid by the importer of record, not the carrier. Connexx calculates duty per SKU against the live tariff before goods arrive.",
    related: [
      { label: "HS code", href: "#hs-code-harmonised-system-code" },
      { label: "UK Global Tariff", href: "#uk-global-tariff" },
      { label: "Landed cost", href: "#landed-cost" },
    ],
  },
  {
    slug: "duty-deferment",
    name: "Duty deferment",
    category: "Customs",
    definition: "An HMRC scheme allowing approved UK importers to defer duty and import VAT payment until the 15th of the following month, paid via direct debit.",
    context: "A Duty Deferment Account (DDA) is essential for any importer doing meaningful volume. It avoids the cash drag of paying duty at every clearance and consolidates payment into one monthly direct debit. Setting up a DDA requires a guarantee from a bank or insurer. Connexx links to your DDA for automatic deferment on every import.",
    related: [
      { label: "PVA", href: "#pva-postponed-vat-accounting" },
      { label: "C79", href: "#c79-vat-certificate" },
      { label: "HMRC", href: "#hmrc" },
      { label: "Import solution", href: "/solutions/import" },
    ],
  },
  {
    slug: "duty-drawback",
    name: "Duty drawback",
    category: "Customs",
    definition: "A refund of import duty paid on goods that are subsequently re-exported from the country, often used by businesses that import components and export finished products.",
    context: "Duty drawback is a cash flow benefit for businesses that import to manufacture and re-export. Claims are made via HMRC against documented imports and matched exports. The paperwork burden is real, which is why many businesses leave money on the table. Connexx tags drawback-eligible shipments and exports the data set for the claim.",
    related: [
      { label: "Duty", href: "#duty" },
      { label: "IPR", href: "#ipr-inward-processing-relief" },
    ],
  },
  {
    slug: "eori-economic-operators-registration-and-identification",
    code: "EORI",
    name: "EORI (Economic Operators Registration and Identification)",
    category: "Customs",
    definition: "The unique identifier issued by HMRC (or any EU customs authority) to a business that imports or exports goods, used on every customs declaration.",
    context: "A UK EORI starts with GB. An EU EORI starts with the country code (DE, FR, IE, and so on). UK exporters to the EU need both, or use the importer's EU EORI under DDP. EORIs are applied for at gov.uk and issued in about three working days. Connexx stores GB and EU EORIs per legal entity and applies the right one per shipment.",
    related: [
      { label: "HMRC", href: "#hmrc" },
      { label: "Commercial invoice", href: "#commercial-invoice" },
      { label: "IOSS", href: "#ioss-import-one-stop-shop" },
      { label: "Export solution", href: "/solutions/export" },
    ],
  },
  {
    slug: "eur1-movement-certificate",
    code: "EUR.1",
    name: "EUR.1 (movement certificate)",
    category: "Customs",
    definition: "A movement certificate proving goods qualify for preferential duty treatment under the UK-EU Trade and Cooperation Agreement or other preferential trade deals.",
    context: "An EUR.1 is required to claim zero duty on UK origin goods entering the EU (or vice versa) above certain consignment values. Below the threshold, a statement on origin on the commercial invoice is enough. Misclaiming origin leads to retrospective duty and penalties. Connexx checks origin claims against the trader's bill of materials before generating the certificate.",
    related: [
      { label: "ATR", href: "#atr-movement-certificate-eu-turkey" },
      { label: "Rules of origin", href: "#rules-of-origin" },
      { label: "Certificate of origin", href: "#certificate-of-origin" },
    ],
  },
  {
    slug: "hmrc",
    name: "HMRC",
    category: "Customs",
    definition: "His Majesty's Revenue and Customs, the UK government department responsible for tax collection and customs.",
    context: "HMRC operates CDS, issues UK EORIs, runs the Duty Deferment scheme, and publishes the UK Global Tariff. Every UK importer and exporter interacts with HMRC, directly or through a customs broker. Connexx connects to HMRC services through certified intermediaries.",
    related: [
      { label: "CDS", href: "#cds-customs-declaration-service" },
      { label: "EORI", href: "#eori-economic-operators-registration-and-identification" },
      { label: "UK Global Tariff", href: "#uk-global-tariff" },
    ],
  },
  {
    slug: "hs-code-harmonised-system-code",
    code: "HS",
    name: "HS code (Harmonised System code)",
    category: "Customs",
    definition: "A globally standardised numeric code (six digits internationally, ten in the UK and EU) that classifies a product for customs and duty purposes.",
    context: "Every international shipment needs an HS code. The first six digits are common across 200+ countries. The next four are country-specific. The UK Global Tariff and the EU's TARIC database hold the duty rate and import controls keyed off each code. Misclassification causes customs holds and incorrect duty payment. Connexx suggests an HS code from the product description and stores the SKU-to-HS mapping for future shipments.",
    related: [
      { label: "Tariff classification", href: "#tariff-classification" },
      { label: "UK Global Tariff", href: "#uk-global-tariff" },
      { label: "Commercial invoice", href: "#commercial-invoice" },
    ],
  },
  {
    slug: "incoterms",
    name: "Incoterms",
    category: "Customs",
    definition: "The International Chamber of Commerce's set of standardised trade terms (DDP, DAP, FCA, EXW, and others) that define who pays for shipping, insurance, and duty on a cross-border sale.",
    context: "Every international sales contract specifies an Incoterm. Incoterms 2020 is the current version. The two most common in eCommerce are DDP (seller pays everything) and DAP (buyer pays duty on delivery). The two most common in B2B are FCA (seller delivers to a named carrier) and EXW (buyer collects). Connexx applies the agreed Incoterm to every shipment automatically.",
    related: [
      { label: "DDP", href: "#ddp-delivered-duty-paid" },
      { label: "DDU", href: "#ddu-delivered-duty-unpaid" },
      { label: "Landed cost", href: "#landed-cost" },
    ],
  },
  {
    slug: "ioss-import-one-stop-shop",
    code: "IOSS",
    name: "IOSS (Import One-Stop Shop)",
    category: "Customs",
    definition: "An EU VAT scheme that lets non-EU sellers charge EU VAT at checkout on B2C consignments under \u20ac150 and remit it monthly via one EU member state, avoiding VAT collection on delivery.",
    context: "IOSS applies to consignments under \u20ac150 sold to EU consumers. The seller registers in any EU member state, charges the destination country's VAT at checkout, and files one monthly IOSS return. The customer pays no extra VAT on delivery. Above \u20ac150, standard import VAT applies. Connexx applies the trader's IOSS number to every qualifying shipment and routes through IOSS-compatible carriers.",
    related: [
      { label: "OSS", href: "#oss-one-stop-shop" },
      { label: "EORI", href: "#eori-economic-operators-registration-and-identification" },
      { label: "DDP", href: "#ddp-delivered-duty-paid" },
      { label: "Export solution", href: "/solutions/export" },
    ],
  },
  {
    slug: "oss-one-stop-shop",
    code: "OSS",
    name: "OSS (One-Stop Shop)",
    category: "Customs",
    definition: "An EU VAT scheme that lets EU-resident businesses report VAT on B2C cross-border EU sales through one quarterly return in their home member state.",
    context: "OSS is for EU businesses selling cross-border within the EU. IOSS is for non-EU businesses selling into the EU. A UK seller with an EU establishment can use OSS for intra-EU B2C sales. Both schemes simplify VAT reporting but require accurate consignment-level data.",
    related: [
      { label: "IOSS", href: "#ioss-import-one-stop-shop" },
      { label: "EORI", href: "#eori-economic-operators-registration-and-identification" },
    ],
  },
  {
    slug: "packing-list",
    name: "Packing list",
    category: "Customs",
    definition: "A document listing the contents of a shipment by line, used by customs to verify the commercial invoice and by warehouses to check goods on arrival.",
    context: "The packing list and the commercial invoice have to match exactly. A discrepancy on weight, count, or description triggers a customs query that can hold the shipment for two days. Connexx generates both documents from the same source data so they cannot disagree.",
    related: [
      { label: "Commercial invoice", href: "#commercial-invoice" },
      { label: "HS code", href: "#hs-code-harmonised-system-code" },
    ],
  },
  {
    slug: "phytosanitary-certificate",
    name: "Phytosanitary certificate",
    category: "Customs",
    definition: "An official certificate confirming that plant-based goods or related products meet the importing country's plant health requirements.",
    context: "Phytosanitary certificates are issued by the Animal and Plant Health Agency (APHA) in the UK. Goods covered include fresh produce, timber, wooden packaging, and many plant-derived ingredients. The certificate is required at the border. Missing it stops the shipment.",
    related: [
      { label: "Pre-clearance", href: "#pre-clearance" },
      { label: "Certificate of origin", href: "#certificate-of-origin" },
    ],
  },
  {
    slug: "pre-clearance",
    name: "Pre-clearance",
    category: "Customs",
    definition: "Submitting and approving a customs declaration before the goods arrive at the border, so the shipment clears on arrival rather than waiting for the declaration to be processed.",
    context: "Pre-clearance is the difference between a same-day clearance and a 48-hour delay. The declaration is filed against the manifest data before the truck or container reaches the port. Connexx pre-clears every import declaration on CDS as soon as the manifest is generated, so goods clear on arrival.",
    related: [
      { label: "CDS", href: "#cds-customs-declaration-service" },
      { label: "Customs hold", href: "#customs-hold" },
      { label: "Import solution", href: "/solutions/import" },
    ],
  },
  {
    slug: "pva-postponed-vat-accounting",
    code: "PVA",
    name: "PVA (Postponed VAT Accounting)",
    category: "Customs",
    definition: "A UK scheme that lets registered importers account for import VAT on the next VAT return instead of paying it at the border.",
    context: "PVA is a cash flow win. Import VAT is no longer paid at the point of import and reclaimed later. It is declared and reclaimed on the same VAT return. The C79 certificate is replaced by a monthly statement on the trader's CDS account. Connexx flags every shipment as PVA-eligible by default and reconciles against the monthly statement.",
    related: [
      { label: "C79", href: "#c79-vat-certificate" },
      { label: "Duty deferment", href: "#duty-deferment" },
      { label: "Import solution", href: "/solutions/import" },
    ],
  },
  {
    slug: "rules-of-origin",
    name: "Rules of origin",
    category: "Customs",
    definition: "The criteria a country uses to determine where goods were produced, which decides whether they qualify for preferential duty under a trade agreement.",
    context: "Under the UK-EU TCA, goods of UK or EU origin qualify for zero duty if they meet the rules of origin (typically a percentage of value added in the country, or a change in tariff heading). Misclaiming origin leads to retrospective duty and penalties. Connexx checks origin claims against the bill of materials for every export.",
    related: [
      { label: "EUR.1", href: "#eur1-movement-certificate" },
      { label: "Certificate of origin", href: "#certificate-of-origin" },
      { label: "Duty", href: "#duty" },
    ],
  },
  {
    slug: "tariff-classification",
    name: "Tariff classification",
    category: "Customs",
    definition: "The process of assigning the correct HS code to a product, against the UK Global Tariff (for imports) or the destination country's tariff (for exports).",
    context: "Classification is harder than it looks. Many products fall into multiple plausible codes. The wrong code can cost a percentage point of duty or trigger an import licence requirement. Connexx classifies from the product description and validates against the UK Global Tariff, storing the SKU-to-HS mapping for future shipments.",
    related: [
      { label: "HS code", href: "#hs-code-harmonised-system-code" },
      { label: "UK Global Tariff", href: "#uk-global-tariff" },
    ],
  },
  {
    slug: "uk-global-tariff",
    code: "UKGT",
    name: "UK Global Tariff",
    category: "Customs",
    definition: "The UK's post-Brexit import tariff, published by HMRC, setting the duty rate and import controls for every HS code on goods entering the UK.",
    context: "The UK Global Tariff replaced the EU's Common External Tariff after Brexit. Many lines were liberalised (zero duty), others retained the EU rate, and some changed structure. Connexx pulls the live UKGT for every import to calculate landed cost.",
    related: [
      { label: "HS code", href: "#hs-code-harmonised-system-code" },
      { label: "Duty", href: "#duty" },
      { label: "Landed cost", href: "#landed-cost" },
    ],
  },
  {
    slug: "windsor-framework",
    name: "Windsor Framework",
    category: "Customs",
    definition: "The 2023 agreement between the UK and the EU that governs the movement of goods between Great Britain and Northern Ireland, replacing parts of the Northern Ireland Protocol.",
    context: "The Windsor Framework introduced the Green Lane (for goods staying in Northern Ireland) and the Red Lane (for goods at risk of moving into the EU). Green Lane goods clear with minimal customs checks. Red Lane goods follow full EU import procedures. Connexx routes Northern Ireland shipments through the correct lane automatically.",
    related: [
      { label: "CDS", href: "#cds-customs-declaration-service" },
      { label: "EORI", href: "#eori-economic-operators-registration-and-identification" },
      { label: "Import solution", href: "/solutions/import" },
    ],
  },
  {
    slug: "bonded-warehouse",
    name: "Bonded warehouse",
    category: "Customs",
    definition: "A secure facility approved by HMRC where dutiable imported goods can be stored without payment of duty until released for UK consumption or re-exported.",
    context: "Bonded warehousing is used by importers who want to defer duty until the point of sale rather than paying on arrival. Common for alcohol, tobacco, electronics, and fashion. Goods in bond can be re-exported with no duty liability. Connexx tracks bonded stock movements and triggers the correct customs procedure at the point of release.",
    related: [
      { label: "Duty", href: "#duty" },
      { label: "Duty deferment", href: "#duty-deferment" },
      { label: "Pre-clearance", href: "#pre-clearance" },
      { label: "Import solution", href: "/solutions/import" },
    ],
  },
  {
    slug: "customs-broker",
    name: "Customs broker",
    category: "Customs",
    definition: "A licensed professional or company authorised to submit customs declarations to HMRC on behalf of an importer or exporter.",
    context: "Most UK importers and exporters use a customs broker rather than filing declarations directly. The broker holds the authorisation, understands CDS, and takes responsibility for the accuracy of the declaration. A bad declaration is still the trader's liability. Connexx connects to HMRC through accredited customs intermediaries and surfaces declaration data to the broker in the format they need.",
    related: [
      { label: "CDS", href: "#cds-customs-declaration-service" },
      { label: "EORI", href: "#eori-economic-operators-registration-and-identification" },
      { label: "Commercial invoice", href: "#commercial-invoice" },
      { label: "Import solution", href: "/solutions/import" },
    ],
  },
  {
    slug: "dap-delivered-at-place",
    code: "DAP",
    name: "DAP (Delivered at Place)",
    category: "Customs",
    definition: "An Incoterm (Incoterms 2020) where the seller delivers goods to a named destination in the buyer's country, with the buyer responsible for paying import duty and VAT on arrival.",
    context: "DAP replaced DDU in Incoterms 2020 and is the most common Incoterm for B2B cross-border shipments. The seller covers freight and insurance; the buyer handles customs clearance and duty. For B2C eCommerce, DAP creates the dreaded doorstep duty bill, which is why DDP has become the preferred term for consumer-facing cross-border shipping.",
    related: [
      { label: "DDP", href: "#ddp-delivered-duty-paid" },
      { label: "DDU", href: "#ddu-delivered-duty-unpaid" },
      { label: "Incoterms", href: "#incoterms" },
    ],
  },
  {
    slug: "dangerous-goods",
    code: "DG",
    name: "Dangerous goods (DG)",
    category: "Customs",
    definition: "Goods classified under IATA (air), IMDG (sea), or ADR (road) regulations as posing a risk, requiring special packaging, labelling, and documentation.",
    context: "Dangerous goods classifications cover lithium batteries, aerosols, flammables, toxics, and hundreds of other categories. The rules differ by transport mode: IATA for air, IMDG for sea, ADR for road. A business shipping lithium batteries in a laptop must declare them correctly or the shipment will be refused or destroyed. Connexx flags DG-classified SKUs at booking and routes them through DG-certified carriers only.",
    related: [
      { label: "Commercial invoice", href: "#commercial-invoice" },
      { label: "HS code", href: "#hs-code-harmonised-system-code" },
      { label: "Packing list", href: "#packing-list" },
    ],
  },
  {
    slug: "trade-and-cooperation-agreement",
    code: "TCA",
    name: "Trade and Cooperation Agreement (TCA)",
    category: "Customs",
    definition: "The 2020 free trade agreement between the UK and the EU that allows zero-tariff trade on goods meeting the rules of origin, while requiring full customs declarations at the border.",
    context: "The TCA means UK-origin goods entering the EU (and vice versa) pay zero duty \u2014 but only if the rules of origin are met and the correct documentation (EUR.1 or statement on origin) accompanies the shipment. The TCA did not eliminate customs checks; it eliminated tariffs for qualifying goods. Businesses that did not change their customs processes after Brexit are still leaving TCA savings on the table.",
    related: [
      { label: "Rules of origin", href: "#rules-of-origin" },
      { label: "EUR.1", href: "#eur1-movement-certificate" },
      { label: "Duty", href: "#duty" },
      { label: "Export solution", href: "/solutions/export" },
    ],
  },
  {
    slug: "cn22-cn23",
    name: "CN22 / CN23",
    category: "Customs",
    definition: "The customs declaration forms used for international postal shipments \u2014 CN22 for low-value items under \u00a3270 and CN23 for higher-value or commercial parcels.",
    context: "CN22 and CN23 are the World Universal Postal Union's standard customs forms, required on all international postal shipments leaving the UK (and entering most countries). The CN22 is a simplified label format. The CN23 is a full declaration with HS codes, weights, and values, and is required above the relevant threshold. Royal Mail, Parcelforce, and PostNL use CN forms. DHL, FedEx, and UPS use their own commercial invoice equivalents. Connexx generates the correct CN form automatically based on parcel value and destination.",
    related: [
      { label: "Commercial invoice", href: "#commercial-invoice" },
      { label: "HS code", href: "#hs-code-harmonised-system-code" },
      { label: "IOSS", href: "#ioss-import-one-stop-shop" },
      { label: "Export solution", href: "/solutions/export" },
    ],
  },
  {
    slug: "gpsr-general-product-safety-regulation",
    code: "GPSR",
    name: "GPSR (General Product Safety Regulation)",
    category: "Customs",
    definition: "An EU regulation (in force from 2024) requiring businesses selling consumer goods into the EU to ensure their products are safe and, for online sellers, to appoint an EU-based responsible person.",
    context: "GPSR replaced the EU's General Product Safety Directive and significantly raises the bar for UK businesses selling into the EU. Online marketplaces (Amazon EU, eBay.de, etc.) now require sellers to have an EU responsible person on record before listing. Products must meet safety labelling and documentation requirements, which flow into the commercial documentation for each shipment. Connexx flags GPSR-relevant shipments and applies the correct responsible person data to the customs pack.",
    related: [
      { label: "Commercial invoice", href: "#commercial-invoice" },
      { label: "Dangerous goods", href: "#dangerous-goods" },
      { label: "Trade and Cooperation Agreement", href: "#trade-and-cooperation-agreement" },
      { label: "Export solution", href: "/solutions/export" },
    ],
  },
  {
    slug: "consolidation",
    name: "Consolidation",
    category: "Operational",
    definition: "Combining multiple smaller shipments into one larger shipment to lower per-unit cost, often used in freight and pallet networks.",
    context: "A 3PL consolidating client deliveries at a hub before final-mile dispatch is one example. Importers consolidating supplier orders into a single container is another. Consolidation cuts cost and increases complexity. Connexx tracks consolidated shipments back to the underlying orders so per-client billing stays accurate.",
    related: [
      { label: "Manifest", href: "#manifest" },
      { label: "Lane", href: "#lane" },
    ],
  },
  {
    slug: "csat",
    code: "CSAT",
    name: "CSAT",
    category: "Operational",
    definition: "Customer Satisfaction score, typically measured by post-delivery survey on a 1-to-5 or 1-to-10 scale.",
    context: "WISMO tickets and delivery exceptions are the biggest drivers of CSAT drops in eCommerce. A clean delivery experience holds CSAT. Repeated tracking failures erode it within a week. Multi-carrier platforms protect CSAT by routing each order through the most reliable carrier on that lane.",
    related: [
      { label: "WISMO", href: "#wismo-where-is-my-order" },
      { label: "SLA", href: "#sla-service-level-agreement" },
    ],
  },
  {
    slug: "dimensional-weight-dim-weight",
    code: "DIM",
    name: "Dimensional weight (DIM weight)",
    category: "Operational",
    definition: "A pricing weight calculated from a parcel's volume rather than its actual weight, used by carriers to price lightweight but bulky shipments.",
    context: "DIM weight is the carrier's defence against being paid to ship empty space. The formula is length x width x height divided by a divisor (typically 5,000 or 6,000 for international, 4,000 for some UK domestic). The carrier charges by the higher of actual or dimensional weight. Connexx applies DIM rules per carrier so the rate engine compares like with like.",
    related: [
      { label: "Volumetric weight", href: "#volumetric-weight" },
      { label: "Rate card", href: "#rate-card" },
    ],
  },
  {
    slug: "dispatch",
    name: "Dispatch",
    category: "Operational",
    definition: "The act of preparing and sending a shipment, including label generation, manifest creation, and handover to the carrier.",
    context: "Dispatch is the verb every UK operator uses. 'Dispatch decisions', 'dispatch team', 'dispatch volume', 'dispatch cutoff'. A dispatch cutoff is the time by which a parcel has to be handed to the carrier to be collected that day. Miss it and the parcel ships tomorrow.",
    related: [
      { label: "Manifest", href: "#manifest" },
      { label: "SLA", href: "#sla-service-level-agreement" },
      { label: "Late Shipment Rate", href: "#late-shipment-rate-lsr" },
    ],
  },
  {
    slug: "fcl--lcl-full--less-than-container-load",
    code: "FCL/LCL",
    name: "FCL / LCL (Full / Less than Container Load)",
    category: "Operational",
    definition: "Sea freight shipping modes where FCL means the shipment fills a 20ft or 40ft container, and LCL means it shares a container with other shippers.",
    context: "FCL is faster and cheaper per cubic metre at high volume. LCL is the option for smaller importers who cannot fill a container. Most UK importers from Asia run LCL until they hit consistent container volume. Connexx integrates with freight forwarders for both modes.",
    related: [
      { label: "LTL", href: "#ltl-less-than-truckload" },
      { label: "Consolidation", href: "#consolidation" },
      { label: "Import solution", href: "/solutions/import" },
    ],
  },
  {
    slug: "lane",
    name: "Lane",
    category: "Operational",
    definition: "A specific shipping route, usually expressed as origin to destination (e.g. UK to Germany), with implications for carrier choice, transit time, and customs treatment.",
    context: "'Lane' is the planning unit for an export or international eCommerce operation. The UK-to-Germany lane needs a different carrier mix from UK-to-US. Lane performance is measured in cost per parcel, transit time, and exception rate. Connexx tracks lane-level performance per carrier in the dashboard.",
    related: [
      { label: "Carrier portal", href: "#carrier-portal" },
      { label: "Consolidation", href: "#consolidation" },
      { label: "SLA", href: "#sla-service-level-agreement" },
    ],
  },
  {
    slug: "ltl-less-than-truckload",
    code: "LTL",
    name: "LTL (Less Than Truckload)",
    category: "Operational",
    definition: "A road freight mode for shipments too large for parcel carriers but too small to fill a truck, typically used for palletised goods through pallet networks.",
    context: "UK LTL runs through pallet networks like Pall-Ex, Palletline, and Palletways. A shipment is collected, taken to a hub, sorted, and trunked to the destination depot for final delivery. LTL economics depend on hub volume. Connexx rate-shops across pallet networks for every B2B shipment.",
    related: [
      { label: "Pallet network", href: "#pallet-network" },
      { label: "FCL / LCL", href: "#fcl--lcl-full--less-than-container-load" },
      { label: "B2B solution", href: "/solutions/b2b" },
    ],
  },
  {
    slug: "manifest",
    name: "Manifest",
    category: "Operational",
    definition: "The list of parcels in a single carrier collection, generated at the end of a dispatch session and presented to the driver.",
    context: "Each carrier requires a daily manifest. Royal Mail generates one through Click and Drop or its OBA system. DPD generates one through its portal. Multi-carrier platforms generate one manifest per carrier per collection automatically. A manifest is the source of truth for that day's volume.",
    related: [
      { label: "Dispatch", href: "#dispatch" },
      { label: "POD", href: "#pod-proof-of-delivery" },
    ],
  },
  {
    slug: "pallet-network",
    name: "Pallet network",
    category: "Operational",
    definition: "A national or international network of haulage businesses that share a central hub to deliver palletised freight, allowing single-pallet shipments at competitive cost.",
    context: "Pall-Ex, Palletline, and Palletways are the dominant UK pallet networks. Each has 80 to 100 member depots across the UK. A shipper books once, the network handles collection, trunking, and delivery. Pallet sizes (quarter, half, full) and timed delivery windows are the main rate variables.",
    related: [
      { label: "LTL", href: "#ltl-less-than-truckload" },
      { label: "POD", href: "#pod-proof-of-delivery" },
      { label: "B2B solution", href: "/solutions/b2b" },
    ],
  },
  {
    slug: "returns-logistics--reverse-logistics",
    name: "Returns logistics / reverse logistics",
    category: "Operational",
    definition: "The process of handling goods sent back from the customer, including return labels, carrier collection, warehouse receipt, and refund or restock decisions.",
    context: "Returns rates in UK eCommerce typically run 8 to 30 per cent depending on category. Returns logistics costs (label, freight, processing, restocking, write-off) can absorb 30 to 50 per cent of the gross margin on returned items. A returns portal that issues pre-paid labels through the right carrier per lane saves cost and reduces friction.",
    related: [
      { label: "WISMO", href: "#wismo-where-is-my-order" },
      { label: "Carrier portal", href: "#carrier-portal" },
      { label: "eCommerce solution", href: "/solutions/ecommerce" },
    ],
  },
  {
    slug: "volumetric-weight",
    name: "Volumetric weight",
    category: "Operational",
    definition: "A synonym for dimensional weight, used by some carriers and freight forwarders to describe volume-based pricing.",
    context: "Volumetric weight and dimensional weight refer to the same calculation, with different divisors per carrier. Royal Mail does not apply volumetric weight on small parcels but DHL, FedEx, and UPS do on international.",
    related: [
      { label: "Dimensional weight", href: "#dimensional-weight-dim-weight" },
      { label: "Rate card", href: "#rate-card" },
    ],
  },
  {
    slug: "wismo-where-is-my-order",
    code: "WISMO",
    name: "WISMO (Where Is My Order)",
    category: "Operational",
    definition: "The customer service ticket category covering 'where is my parcel?' enquiries from customers waiting for a delivery.",
    context: "WISMO is the single largest CS ticket type for any UK eCommerce brand. At 80 tickets a day across four carriers, a CS team can spend five hours daily looking up tracking. The fix is a single tracking view inside the helpdesk, fed by the multi-carrier platform's tracking data. Peak Commerce cut WISMO tickets by 68 per cent on Connexx.",
    related: [
      { label: "Tracking number / consignment reference", href: "#tracking-number--consignment-reference" },
      { label: "CSAT", href: "#csat" },
      { label: "eCommerce solution", href: "/solutions/ecommerce" },
    ],
  },
  {
    slug: "3pl-third-party-logistics",
    code: "3PL",
    name: "3PL (Third-Party Logistics)",
    category: "Operational",
    definition: "An outsourced logistics provider that handles warehousing, pick and pack, and carrier dispatch on behalf of a brand or retailer.",
    context: "A 3PL takes on the physical fulfilment operation \u2014 goods in, storage, pick and pack, despatch, and returns \u2014 so the brand does not need its own warehouse. Most UK 3PLs operate multi-client warehouses and share carrier rate cards across their clients. Connexx manages unlimited client accounts under one 3PL contract with separate billing and reporting per brand.",
    related: [
      { label: "Child account", href: "#child-account" },
      { label: "WMS", href: "#wms-warehouse-management-system" },
      { label: "Pick and pack", href: "#pick-and-pack" },
      { label: "3PL solution", href: "/solutions/3pl" },
    ],
  },
  {
    slug: "click-and-collect",
    name: "Click and Collect",
    category: "Operational",
    definition: "A fulfilment model where the customer purchases online and collects the order from a retail store, carrier drop-off point, or parcel locker.",
    context: "Click and Collect reduces last-mile cost for the retailer and gives the customer flexibility on collection time. Carrier drop-off networks (Evri ParcelShop, InPost lockers, Royal Mail Customer Service Points) handle the bulk of non-store click and collect in UK eCommerce. Connexx routes click-and-collect orders to the correct drop-off carrier automatically at checkout.",
    related: [
      { label: "Drop-off", href: "#drop-off-parcelshop-locker" },
      { label: "Last mile", href: "#last-mile" },
      { label: "Returns logistics / reverse logistics", href: "#returns-logistics--reverse-logistics" },
      { label: "eCommerce solution", href: "/solutions/ecommerce" },
    ],
  },
  {
    slug: "fba-fulfilled-by-amazon",
    code: "FBA",
    name: "FBA (Fulfilled by Amazon)",
    category: "Operational",
    definition: "Amazon's fulfilment service where the seller sends inventory to Amazon warehouses and Amazon handles storage, pick and pack, and delivery.",
    context: "FBA is the fastest route to Prime eligibility, but it comes with storage fees, removal fees, and limited SKU visibility. Sellers using FBA for Amazon and self-fulfilling for other channels need a multi-carrier platform that handles the non-FBA dispatch queue. Connexx routes non-FBA orders across Royal Mail, DPD, Evri, and others from the same interface.",
    related: [
      { label: "Seller Fulfilled Prime", href: "#seller-fulfilled-prime-sfp" },
      { label: "Buy Shipping", href: "#buy-shipping-amazon" },
      { label: "3PL", href: "#3pl-third-party-logistics" },
      { label: "Marketplace seller solution", href: "/solutions/marketplace-seller" },
    ],
  },
  {
    slug: "last-mile",
    name: "Last mile",
    category: "Operational",
    definition: "The final leg of a parcel's journey from a carrier's local depot to the delivery address, the most expensive and failure-prone stage in the delivery chain.",
    context: "Last mile accounts for over half of total delivery cost per parcel in most UK operations. It is where delays, failed attempts, and exceptions concentrate. Carrier choice at the last-mile level \u2014 door-to-door, parcel locker, or ParcelShop \u2014 is the most consequential routing decision for eCommerce cost and CSAT. Connexx routes each order through the last-mile option that best fits the customer's address, cost target, and SLA.",
    related: [
      { label: "Delivery exception", href: "#delivery-exception" },
      { label: "WISMO", href: "#wismo-where-is-my-order" },
      { label: "CSAT", href: "#csat" },
      { label: "eCommerce solution", href: "/solutions/ecommerce" },
    ],
  },
  {
    slug: "pick-and-pack",
    name: "Pick and pack",
    category: "Operational",
    definition: "The warehouse process of selecting the correct items from stock (picking) and packing them into a box or bag ready for carrier collection.",
    context: "Pick and pack is the core labour cost in a fulfilment operation. Accuracy at pick and pack prevents mis-picks, short shipments, and returns. A WMS drives pick accuracy; a shipping platform takes the packed order and generates the label. Connexx integrates with all major WMS platforms so the dispatch trigger flows automatically from the packing station.",
    related: [
      { label: "WMS", href: "#wms-warehouse-management-system" },
      { label: "Dispatch", href: "#dispatch" },
      { label: "3PL", href: "#3pl-third-party-logistics" },
      { label: "3PL solution", href: "/solutions/3pl" },
    ],
  },
  {
    slug: "sku-stock-keeping-unit",
    code: "SKU",
    name: "SKU (Stock Keeping Unit)",
    category: "Operational",
    definition: "A unique identifier assigned by a business to each distinct product variant to manage inventory, orders, and fulfilment across systems.",
    context: "A SKU ties together the product master, the warehouse pick location, the HS code for customs, and the carrier routing rule. A business with 10,000 SKUs across three warehouses and four carriers needs every system to speak the same SKU. Connexx stores the SKU-to-HS mapping for customs, the SKU-to-weight for carrier rating, and the SKU-to-routing rule for dispatch \u2014 all in one place.",
    related: [
      { label: "HS code", href: "#hs-code-harmonised-system-code" },
      { label: "WMS", href: "#wms-warehouse-management-system" },
      { label: "Rate engine", href: "#rate-engine" },
    ],
  },
  {
    slug: "air-freight",
    name: "Air freight",
    category: "Operational",
    definition: "The movement of cargo by aircraft, used where speed or urgency outweighs the cost premium over sea freight.",
    context: "Air freight costs 4 to 6 times more per kilogram than sea freight but delivers in 1 to 5 days versus 20 to 40 days. UK importers from China use air freight for fast-moving stock, seasonal launches, and sample shipments. ITD Global operates a weekly consolidated air freight service from China (the Console Sample Service) that gives smaller importers access to air rates normally reserved for high-volume buyers.",
    related: [
      { label: "FCL / LCL", href: "#fcl--lcl-full--less-than-container-load" },
      { label: "Consolidation", href: "#consolidation" },
      { label: "Landed cost", href: "#landed-cost" },
      { label: "Import solution", href: "/solutions/import" },
    ],
  },
  {
    slug: "bill-of-lading-bol",
    code: "BOL",
    name: "Bill of Lading (BOL)",
    category: "Operational",
    definition: "A legal document issued by a carrier to a shipper, serving as a contract of carriage, a receipt of goods, and a title document that can be used to claim the shipment at destination.",
    context: "The BOL is the most important document in sea freight. It records what was loaded, the agreed terms of carriage, and who holds title to the goods. In B2B road freight, a simplified delivery note (sometimes called a BOL or CMR note) travels with the consignment. In pallet network deliveries, the BOL includes the booking-in reference that retail RDCs require to accept the goods. Connexx generates the BOL and embeds the booking-in reference automatically for B2B consignments.",
    related: [
      { label: "Commercial invoice", href: "#commercial-invoice" },
      { label: "Packing list", href: "#packing-list" },
      { label: "Consignment", href: "#consignment" },
      { label: "RDC", href: "#rdc-regional-distribution-centre" },
      { label: "B2B solution", href: "/solutions/b2b" },
    ],
  },
  {
    slug: "buyers-consolidation",
    name: "Buyers consolidation",
    category: "Operational",
    definition: "An import freight model where a logistics provider collects goods from multiple suppliers in the origin country and combines them into a single container or shipment before departure.",
    context: "Buyers consolidation is common for UK importers sourcing from several Chinese factories at similar times. Instead of each factory booking a separate LCL shipment, the logistics provider collects from each factory, consolidates at an origin warehouse (e.g. in Shenzhen), and ships as a single FCL or LCL movement. The result is one invoice, one customs entry, and a lower landed cost per unit. ITD Global manages buyers consolidations from its China office directly.",
    related: [
      { label: "FCL / LCL", href: "#fcl--lcl-full--less-than-container-load" },
      { label: "Consolidation", href: "#consolidation" },
      { label: "Landed cost", href: "#landed-cost" },
      { label: "Import solution", href: "/solutions/import" },
    ],
  },
  {
    slug: "rdc-regional-distribution-centre",
    code: "RDC",
    name: "RDC (Regional Distribution Centre)",
    category: "Operational",
    definition: "A large warehouse hub operated by a major retailer (e.g. Tesco, Sainsbury's, Next) that receives supplier deliveries and redistributes stock to its store network.",
    context: "Supplying into an RDC is the standard route into UK supermarket and major retail chains. Each retailer has its own booking-in system, labelling requirements, delivery windows, and compliance rules. A failed or mis-timed delivery to an RDC typically triggers a chargeback. B2B shippers using Connexx embed the retailer's booking-in reference on the BOL and select a carrier that meets the RDC's delivery window SLA.",
    related: [
      { label: "Bill of Lading", href: "#bill-of-lading-bol" },
      { label: "SLA", href: "#sla-service-level-agreement" },
      { label: "POD", href: "#pod-proof-of-delivery" },
      { label: "B2B solution", href: "/solutions/b2b" },
    ],
  },
  {
    slug: "sea-freight",
    name: "Sea freight",
    category: "Operational",
    definition: "The movement of cargo by container ship, the most cost-efficient mode for large international volumes where transit time is flexible.",
    context: "Sea freight is the backbone of global trade. Most UK imports from China, Southeast Asia, and other long-haul origins move by sea. A standard 20ft container carries roughly 25 to 28 tonnes or 33 cubic metres. Transit times from China to the UK run 28 to 35 days by the Suez route. ITD Global manages FCL, LCL, and buyers consolidation sea freight through its China office.",
    related: [
      { label: "FCL / LCL", href: "#fcl--lcl-full--less-than-container-load" },
      { label: "Buyers consolidation", href: "#buyers-consolidation" },
      { label: "Landed cost", href: "#landed-cost" },
      { label: "Import solution", href: "/solutions/import" },
    ],
  },
  {
    slug: "api-application-programming-interface",
    code: "API",
    name: "API (Application Programming Interface)",
    category: "Technical",
    definition: "A set of endpoints that lets one software system talk to another, used in shipping to connect order systems (Shopify, NetSuite) to carriers and platforms (Royal Mail, DPD, Connexx).",
    context: "Every modern carrier publishes an API. Every modern platform consumes them. A platform with native API connections beats one that uses CSV uploads, because the data flows in real time and writes back automatically. Connexx exposes its own REST API to customers who want to build custom workflows.",
    related: [
      { label: "RESTful API", href: "#restful-api" },
      { label: "Webhook", href: "#webhook" },
      { label: "ERP write-back", href: "#erp-write-back" },
    ],
  },
  {
    slug: "erp-write-back",
    name: "ERP write-back",
    category: "Technical",
    definition: "The process by which a shipping platform writes shipment data (tracking numbers, dispatch dates, costs, POD) back into the source ERP, so the order record is updated automatically.",
    context: "Without write-back, dispatch teams re-key tracking numbers into the ERP by hand. With write-back, the data flows. NetSuite and other major ERPs support write-back through API or middleware. Connexx supports two-way sync with every major ERP.",
    related: [
      { label: "API", href: "#api-application-programming-interface" },
      { label: "Webhook", href: "#webhook" },
      { label: "Tracking number / consignment reference", href: "#tracking-number--consignment-reference" },
    ],
  },
  {
    slug: "oms-order-management-system",
    code: "OMS",
    name: "OMS (Order Management System)",
    category: "Technical",
    definition: "A software platform that aggregates orders from multiple sales channels (Shopify, Amazon, eBay, B2B portal) into one queue for dispatch.",
    context: "Linnworks, Veeqo, StoreFeeder, and Selro are the dominant UK OMS platforms for multi-channel sellers. The OMS holds the order until it is ready for dispatch. The shipping platform takes the dispatched order, picks the carrier, generates the label, and writes the tracking number back. Connexx integrates with every major OMS.",
    related: [
      { label: "WMS", href: "#wms-warehouse-management-system" },
      { label: "API", href: "#api-application-programming-interface" },
    ],
  },
  {
    slug: "restful-api",
    code: "REST",
    name: "RESTful API",
    category: "Technical",
    definition: "A style of web API that uses standard HTTP methods (GET, POST, PUT, DELETE) and JSON payloads, the dominant pattern in modern software integration.",
    context: "A REST API is the easiest pattern to integrate against. Connexx's API is REST. Most modern carrier APIs are REST. Older carrier APIs use SOAP or proprietary XML, which Connexx handles internally so the customer never sees them.",
    related: [
      { label: "API", href: "#api-application-programming-interface" },
      { label: "Webhook", href: "#webhook" },
    ],
  },
  {
    slug: "webhook",
    name: "Webhook",
    category: "Technical",
    definition: "An HTTP callback that one system sends to another when an event occurs (e.g. an order is created in Shopify, a parcel is scanned by DPD), enabling real-time data flow without polling.",
    context: "Webhooks are how shipping platforms get instant notification of order creation, dispatch, and delivery. Connexx receives Shopify order-created webhooks and pushes tracking events back via webhooks to the customer's ERP. Real-time webhook flow beats hourly batch polling for any time-sensitive workflow.",
    related: [
      { label: "API", href: "#api-application-programming-interface" },
      { label: "ERP write-back", href: "#erp-write-back" },
    ],
  },
  {
    slug: "wms-warehouse-management-system",
    code: "WMS",
    name: "WMS (Warehouse Management System)",
    category: "Technical",
    definition: "A software platform that manages warehouse operations including stock locations, picking, packing, and inventory accuracy.",
    context: "Mintsoft, ShipHero, Manhattan Active Warehouse, and Blue Yonder are the UK-relevant WMS platforms. A WMS controls what is on the shelf and where it goes. A shipping platform controls how it gets to the customer. The two systems integrate so an order picked in the WMS dispatches through the shipping platform automatically. Connexx integrates with every major WMS.",
    related: [
      { label: "OMS", href: "#oms-order-management-system" },
      { label: "API", href: "#api-application-programming-interface" },
      { label: "3PL solution", href: "/solutions/3pl" },
    ],
  },
  {
    slug: "edi-electronic-data-interchange",
    code: "EDI",
    name: "EDI (Electronic Data Interchange)",
    category: "Technical",
    definition: "A standardised format for exchanging business documents (purchase orders, invoices, despatch advice) between companies electronically, without human re-keying.",
    context: "EDI is the integration standard demanded by most major UK retailers and grocery buyers. If a supplier cannot receive an EDI purchase order and send back an EDI despatch advice, they cannot trade with Tesco, Asda, or Marks & Spencer in volume. EDI predates APIs but is still prevalent in B2B supply chains. Connexx maps EDI despatch advice messages to carrier bookings automatically.",
    related: [
      { label: "API", href: "#api-application-programming-interface" },
      { label: "ERP write-back", href: "#erp-write-back" },
      { label: "OMS", href: "#oms-order-management-system" },
      { label: "B2B solution", href: "/solutions/b2b" },
    ],
  },
  {
    slug: "tracking-event",
    name: "Tracking event",
    category: "Technical",
    definition: "A timestamped status update from the carrier (collected, in transit, out for delivery, delivered) that feeds customer-facing tracking pages and internal dashboards.",
    context: "A parcel in transit generates between 5 and 15 tracking events depending on the carrier and service. Each event has a status code, a timestamp, and a location. Connexx normalises event codes across all carriers into a consistent set so a 'delivered' event means the same thing whether it came from DPD, Evri, or Royal Mail. Tracking event gaps \u2014 parcels with no scan for 24+ hours \u2014 are surfaced automatically in the Connexx exception dashboard.",
    related: [
      { label: "Tracking number / consignment reference", href: "#tracking-number--consignment-reference" },
      { label: "WISMO", href: "#wismo-where-is-my-order" },
      { label: "Webhook", href: "#webhook" },
    ],
  },
  {
    slug: "label-format-zpl-pdf",
    code: "ZPL",
    name: "Label format (ZPL / PDF)",
    category: "Technical",
    definition: "The specification for a shipping label, including physical size (typically A6 or 6x4 inch), file format (ZPL for thermal printers or PDF for laser), and carrier-required layout.",
    context: "Every carrier prescribes its own label layout, barcode format, and data fields. Royal Mail uses a 6x4 ZPL for most services. DPD uses A6 ZPL. Some carriers require PDF labels at specific DPI settings. Mismatch between label format and printer capability causes unreadable barcodes. Connexx generates the correct label format per carrier automatically, regardless of printer setup.",
    related: [
      { label: "API", href: "#api-application-programming-interface" },
      { label: "Dispatch", href: "#dispatch" },
      { label: "Manifest", href: "#manifest" },
    ],
  },
  {
    slug: "branded-tracking-page",
    name: "Branded tracking page",
    category: "Technical",
    definition: "A shipment tracking page hosted under the retailer's or 3PL's own domain and branding, rather than the carrier's generic tracking URL.",
    context: "A branded tracking page keeps the customer on the retailer's experience after dispatch, reducing WISMO calls and creating a marketing opportunity (product recommendations, loyalty schemes). The page pulls real-time tracking events from the carrier via the shipping platform's API. Connexx generates a branded tracking URL for every shipment and can host it on the retailer's domain, regardless of which carrier is carrying the parcel.",
    related: [
      { label: "Tracking event", href: "#tracking-event" },
      { label: "WISMO", href: "#wismo-where-is-my-order" },
      { label: "CSAT", href: "#csat" },
      { label: "eCommerce solution", href: "/solutions/ecommerce" },
    ],
  },
  {
    slug: "customs-hold",
    name: "Customs hold",
    category: "Regulatory",
    definition: "A delay imposed by customs authorities (HMRC or the destination country's customs) on a shipment that fails initial checks, pending resolution of a documentation or compliance issue.",
    context: "Customs holds typically take 24 to 72 hours to resolve and require additional paperwork. The most common causes are misclassified HS codes, missing or wrong EORI, mismatched commercial invoice and packing list, and missing certificates. SwiftLog Fulfilment lifted customs accuracy from 93 per cent to 98.7 per cent on Connexx, cutting customs-related delays by 85 per cent.",
    related: [
      { label: "Pre-clearance", href: "#pre-clearance" },
      { label: "HS code", href: "#hs-code-harmonised-system-code" },
      { label: "Commercial invoice", href: "#commercial-invoice" },
    ],
  },
  {
    slug: "landed-cost",
    name: "Landed cost",
    category: "Regulatory",
    definition: "The total cost of getting goods from a supplier to the final destination, including supplier price, freight, insurance, duty, import VAT, customs fees, and any surcharges.",
    context: "Landed cost matters most for importers pricing products against margin. Estimates that are off by 10 to 20 per cent erode margin on every unit until the next price review. Northgate Imports lifted duty cost accuracy from 82 per cent to 97 per cent on Connexx, which let finance price every SKU against accurate margin.",
    related: [
      { label: "Duty", href: "#duty" },
      { label: "UK Global Tariff", href: "#uk-global-tariff" },
      { label: "Import solution", href: "/solutions/import" },
    ],
  },
  {
    slug: "surcharge-zone",
    name: "Surcharge zone",
    category: "Regulatory",
    definition: "A geographic area (typically postcodes) outside the carrier's standard delivery network, where the carrier applies an additional fee per shipment.",
    context: "Highlands, Islands, Channel Islands, Northern Ireland, and BFPO are the main UK surcharge zones. Each carrier has its own list. Routing rules in a multi-carrier platform pick the carrier with the lowest surcharge for the destination postcode.",
    related: [
      { label: "Highlands & Islands", href: "#highlands--islands" },
      { label: "Out-of-area", href: "#out-of-area" },
      { label: "Mainland UK", href: "#mainland-uk" },
    ],
  },
  {
    slug: "ipr-inward-processing-relief",
    code: "IPR",
    name: "IPR (Inward Processing Relief)",
    category: "Regulatory",
    definition: "An HMRC scheme allowing UK importers to suspend or refund duty on goods imported for processing and re-export.",
    context: "IPR is for businesses that import components, process them in the UK, and export the finished product. Duty on the imported components is either suspended at import or refunded later. The paperwork burden is meaningful, which is why many eligible businesses do not use the scheme. Connexx tags IPR-eligible shipments for the claim.",
    related: [
      { label: "Duty drawback", href: "#duty-drawback" },
      { label: "OPR", href: "#opr-outward-processing-relief" },
    ],
  },
  {
    slug: "opr-outward-processing-relief",
    code: "OPR",
    name: "OPR (Outward Processing Relief)",
    category: "Regulatory",
    definition: "An HMRC scheme allowing UK exporters to send goods abroad for processing and re-import them with duty calculated only on the value added abroad, not the full re-import value.",
    context: "OPR is the export counterpart to IPR. Used by businesses that send raw materials or components abroad for finishing and then re-import. Common in fashion, electronics assembly, and machinery. Connexx flags OPR-eligible movements and tracks them through the re-import.",
    related: [
      { label: "IPR", href: "#ipr-inward-processing-relief" },
      { label: "Duty", href: "#duty" },
    ],
  },
  {
    slug: "consumer-rights-act-2015",
    code: "CRA",
    name: "Consumer Rights Act 2015",
    category: "Regulatory",
    definition: "UK legislation that sets minimum standards for goods sold online, including the seller's liability when a parcel is lost, damaged, or significantly delayed.",
    context: "Under the Consumer Rights Act, the retailer \u2014 not the carrier \u2014 is liable to the customer for non-delivery or damaged goods. The customer's contract is with the retailer. This is why retailers need carrier claims processes that are fast and well-documented. Connexx surfaces POD, exception events, and carrier liability data in one place so customer service teams can resolve claims in minutes rather than days.",
    related: [
      { label: "POD", href: "#pod-proof-of-delivery" },
      { label: "Delivery exception", href: "#delivery-exception" },
      { label: "Returns logistics / reverse logistics", href: "#returns-logistics--reverse-logistics" },
      { label: "eCommerce solution", href: "/solutions/ecommerce" },
    ],
  },
  {
    slug: "epr-extended-producer-responsibility",
    code: "EPR",
    name: "EPR (Extended Producer Responsibility)",
    category: "Regulatory",
    definition: "A UK regulation requiring producers, importers, and large sellers of packaging to register with a compliance scheme and pay fees based on the weight and type of packaging they place on the UK market.",
    context: "EPR for packaging came into force for large organisations in 2024 and expands to SMEs on a phased schedule. Importers are classed as producers of the packaging their goods arrive in. The data requirement \u2014 packaging type, material, weight per SKU \u2014 sits at the intersection of customs and operational data. Connexx captures packaging data at the SKU level and exports it in the format compliance schemes require.",
    related: [
      { label: "SKU", href: "#sku-stock-keeping-unit" },
      { label: "Landed cost", href: "#landed-cost" },
      { label: "HMRC", href: "#hmrc" },
    ],
  },
  {
    slug: "uk-gdpr",
    code: "GDPR",
    name: "UK GDPR",
    category: "Regulatory",
    definition: "The UK's data protection law, retained from EU GDPR after Brexit, governing how businesses collect, store, and use personal data \u2014 including customer names and delivery addresses in shipping workflows.",
    context: "Shipping workflows handle personal data at every stage: customer name and address on the label, delivery notification by SMS or email, tracking page access. Carriers, platforms, and ERPs are all data processors under UK GDPR. A data breach involving shipping data \u2014 including a carrier losing a parcel manifest \u2014 is notifiable to the ICO. Connexx encrypts all personal data in transit and at rest and supports data subject access requests across shipment history.",
    related: [
      { label: "EORI", href: "#eori-economic-operators-registration-and-identification" },
      { label: "Commercial invoice", href: "#commercial-invoice" },
      { label: "Customs hold", href: "#customs-hold" },
    ],
  },
];
