"use client";

import { useEffect, useRef, useState } from "react";
import { BarChart3, Truck, MapPin, Plug, type LucideIcon } from "lucide-react";
import IntelligenceAnimation from "@/components/sections/IntelligenceAnimation";
import DispatchAnimation from "@/components/sections/DispatchAnimation";

/**
 * Connexx feature explorer. Replaces the old stack of four scrolling
 * "module deep dive" sections with a single in-place switcher: a menu rail of
 * the four modules and a panel that swaps to the selected module's copy and
 * live UI preview — the page doesn't grow as you move between features.
 */

type Feature = {
  icon: LucideIcon;
  name: string;
  summary: string;
  lead: string;
  bullets: string[];
  preview?: "intelligence" | "dispatch";
};

const FEATURES: Feature[] = [
  {
    icon: BarChart3,
    name: "Intelligence",
    summary:
      "A live view of what you're shipping, with problem parcels flagged before your customers chase them.",
    lead: "A live view of everything you ship, with the parcels that need attention surfaced before your customers chase you.",
    bullets: [
      "Label volume broken down by carrier, service, order source and destination, with UK and worldwide delivery maps and CSV export on each view.",
      "Filter by labels printed or all shipments, over 1, 7, 14 or 30 days, or a full year.",
      "The Exceptions view tracks your delivery rate and flags parcels that have gone quiet, so a stuck order shows up before the buyer emails in.",
      "Open exceptions are grouped by who can act on them, so your team goes straight to the ones they can move.",
      "An action queue lists the longest-stuck parcels first, with barcode, carrier, destination and last tracking event.",
    ],
    preview: "intelligence",
  },
  {
    icon: Truck,
    name: "Multi-Carrier Dispatch",
    summary:
      "Labels for the carriers you ship with, from one screen, in whatever format each needs.",
    lead: "One place to dispatch across the carriers you ship with, in the label format and manifest each one needs.",
    bullets: [
      "16 live carrier integrations, UK and international.",
      "One-click label generation, with batch processing for peak volume.",
      "Manifests generated by date range or by shipment IDs.",
      "Failed dispatches are flagged per parcel with the carrier's error, so your team can fix and rebook before the order gets lost in a batch.",
    ],
    preview: "dispatch",
  },
  {
    icon: MapPin,
    name: "Integrated Tracking",
    summary:
      "One place to track across your carriers, without chasing separate courier sites.",
    lead: "One tracking view across your carriers, with live status pulled straight from the source.",
    bullets: [
      "Live tracking events pulled directly from the carrier APIs, with automatic fallback to stored data when a live feed has nothing new yet.",
      "Each carrier's status codes are normalised into one set, so “Delivered” or “Exception” means the same thing whichever carrier it came from.",
      "A real-time push the moment a label job or batch completes, so no one refreshes a screen to check.",
      "Status updates and tracking codes push to your own systems via webhook, alongside the label and shipment data.",
    ],
  },
  {
    icon: Plug,
    name: "Store & Workflow Connectivity",
    summary:
      "Shopify, eBay, Temu and your own systems connect via API, with rules that route each shipment to the right carrier.",
    lead: "Native integrations where it matters, an API for the rest.",
    bullets: [
      "Native, OAuth-connected integrations with Shopify, eBay and Temu pull orders in and push shipment status back automatically.",
      "A REST API covers shipment creation, cancellation, carrier lookup and tracking, so any system you run can plug straight in.",
      "Routing rules match each shipment to a carrier and service on conditions like weight and warehouse, flagging anything that doesn't fit for review.",
      "Import profiles map incoming order data to Connexx's shipment fields, so a new order source isn't a custom engineering job.",
    ],
  },
];

export default function ConnexxFeatures() {
  const [active, setActive] = useState(0);
  const [shown, setShown] = useState(true);
  const tabRefs = useRef<(HTMLButtonElement | null)[]>([]);

  // Fade the panel on switch (no layout dependency on globals.css keyframes).
  useEffect(() => {
    setShown(false);
    const id = requestAnimationFrame(() => setShown(true));
    return () => cancelAnimationFrame(id);
  }, [active]);

  const move = (dir: 1 | -1) => {
    const next = (active + dir + FEATURES.length) % FEATURES.length;
    setActive(next);
    tabRefs.current[next]?.focus();
  };

  const onKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "ArrowDown" || e.key === "ArrowRight") {
      e.preventDefault();
      move(1);
    } else if (e.key === "ArrowUp" || e.key === "ArrowLeft") {
      e.preventDefault();
      move(-1);
    }
  };

  const f = FEATURES[active];
  const Icon = f.icon;

  return (
    <section className="bg-white py-16 md:py-24 border-t border-border" aria-labelledby="connexx-features-heading">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="mb-10 md:mb-12 max-w-2xl">
          <p className="text-eyebrow text-accent mb-2">The platform, module by module</p>
          <h2 id="connexx-features-heading" className="text-display-lg text-text-primary">
            Explore each feature
          </h2>
          <p className="mt-3 text-body-md text-text-secondary">
            Pick a module to see what it does and how it looks in Connexx. Everything updates in place.
          </p>
        </div>

        <div className="grid gap-6 lg:grid-cols-[300px_1fr] lg:gap-10">
          {/* Menu rail — horizontal scroll on mobile, vertical list on desktop */}
          <div
            role="tablist"
            aria-label="Connexx modules"
            aria-orientation="vertical"
            onKeyDown={onKeyDown}
            className="flex gap-2 overflow-x-auto pb-2 lg:flex-col lg:overflow-visible lg:pb-0"
          >
            {FEATURES.map((feat, i) => {
              const FIcon = feat.icon;
              const on = i === active;
              return (
                <button
                  key={feat.name}
                  ref={(el) => {
                    tabRefs.current[i] = el;
                  }}
                  role="tab"
                  id={`connexx-tab-${i}`}
                  aria-selected={on}
                  aria-controls="connexx-tabpanel"
                  tabIndex={on ? 0 : -1}
                  onClick={() => setActive(i)}
                  className={`group flex-none lg:flex-auto text-left rounded-xl border p-4 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent ${
                    on
                      ? "border-accent/40 bg-accent-light/50"
                      : "border-border bg-white hover:border-accent/20 hover:bg-bg-secondary/60"
                  }`}
                >
                  <div className="flex items-center gap-2.5">
                    <FIcon className={`w-5 h-5 flex-none ${on ? "text-accent" : "text-text-tertiary group-hover:text-accent"}`} strokeWidth={1.75} />
                    <span className={`text-sm font-semibold whitespace-nowrap lg:whitespace-normal ${on ? "text-text-primary" : "text-text-secondary"}`}>
                      {feat.name}
                    </span>
                  </div>
                  <p className="mt-2 hidden lg:block text-body-sm text-text-tertiary">
                    {feat.summary}
                  </p>
                </button>
              );
            })}
          </div>

          {/* Panel — swaps in place */}
          <div
            role="tabpanel"
            id="connexx-tabpanel"
            aria-labelledby={`connexx-tab-${active}`}
            className="min-w-0"
          >
            <div
              key={active}
              style={{ opacity: shown ? 1 : 0, transition: "opacity 0.3s ease" }}
            >
              <Icon className="w-9 h-9 text-accent mb-3" strokeWidth={1.75} />
              <p className="text-eyebrow text-accent mb-1.5">
                Module {String(active + 1).padStart(2, "0")}
              </p>
              <h3 className="text-display-md text-text-primary">{f.name}</h3>
              <p className="mt-2 text-body-md text-text-secondary max-w-2xl">{f.lead}</p>

              <div className="mt-6">
                {f.preview === "intelligence" ? (
                  <IntelligenceAnimation />
                ) : f.preview === "dispatch" ? (
                  <DispatchAnimation />
                ) : (
                  <div className="rounded-2xl border border-border bg-bg-secondary flex items-center justify-center aspect-[1152/702]">
                    <div className="text-center">
                      <Icon className="w-16 h-16 text-accent/20 mx-auto mb-3" strokeWidth={1.5} />
                      <p className="text-body-sm text-text-tertiary">{f.name} — UI preview</p>
                    </div>
                  </div>
                )}
              </div>

              <ul className="mt-6 grid gap-x-10 gap-y-3 sm:grid-cols-2">
                {f.bullets.map((b) => (
                  <li key={b} className="flex items-start gap-3">
                    <span className="text-accent mt-1 flex-shrink-0">&#10003;</span>
                    <span className="text-text-secondary text-sm leading-relaxed">{b}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
