// One-off generator: projects the UK boundary + carrier-hub cities into a fixed
// SVG viewBox and writes src/lib/uk-geo.ts (no runtime dependency on d3).
// Run:  node scripts/gen-uk-geo.mjs   (needs /tmp/countries-50m.json + dev deps)
import { readFileSync, writeFileSync } from "node:fs";
import { feature } from "topojson-client";
import { geoMercator, geoPath } from "d3-geo";

const topo = JSON.parse(readFileSync("/tmp/countries-50m.json", "utf8"));
const fc = feature(topo, topo.objects.countries);
const uk = fc.features.find((f) => String(f.id) === "826"); // United Kingdom
if (!uk) throw new Error("UK (826) not found in world-atlas");

const W = 380;
const H = 480;
const proj = geoMercator().fitExtent(
  [
    [16, 16],
    [W - 16, H - 16],
  ],
  uk,
);
const d = geoPath(proj)(uk);

const cityList = [
  ["London", 51.5074, -0.1278, true],
  ["Manchester", 53.4808, -2.2426],
  ["Birmingham", 52.4862, -1.8904],
  ["Leeds", 53.8008, -1.5491],
  ["Glasgow", 55.8642, -4.2518],
  ["Edinburgh", 55.9533, -3.1883],
  ["Belfast", 54.5973, -5.9301],
  ["Cardiff", 51.4816, -3.1791],
  ["Bristol", 51.4545, -2.5879],
  ["Newcastle", 54.9783, -1.6178],
];
const cities = cityList.map(([name, lat, lng, hub]) => {
  const [x, y] = proj([lng, lat]);
  return { name, x: +x.toFixed(1), y: +y.toFixed(1), hub: !!hub };
});

const out = `// AUTO-GENERATED by scripts/gen-uk-geo.mjs — do not edit by hand.
export const UK_VIEWBOX = "0 0 ${W} ${H}";
export const UK_PATH = ${JSON.stringify(d)};
export interface UKCity { name: string; x: number; y: number; hub?: boolean }
export const UK_CITIES: UKCity[] = ${JSON.stringify(cities, null, 2)};
`;
writeFileSync("src/lib/uk-geo.ts", out);
console.log("wrote src/lib/uk-geo.ts — path chars:", d.length, "cities:", cities.length);
