import Link from "next/link";
import { RATE_CHECKER_URL } from "@/lib/site-config";
import Button from "@/components/ui/Button";
import ScrollReveal from "@/components/animations/ScrollReveal";
import AnimatedCounter from "@/components/ui/AnimatedCounter";
import FullOverviewAnimation from "@/components/sections/FullOverviewAnimation";
import MagneticButton from "@/components/ui/MagneticButton";
import ClosingCTA from "@/components/sections/ClosingCTA";
import ConnexxOrbit from "@/components/sections/ConnexxOrbit";
import FaqSection from "@/components/sections/FaqSection";
import ConnexxFeatures from "@/components/sections/ConnexxFeatures";
import { buildMetadata } from "@/lib/metadata";
import {
  JsonLd,
  productSchema,
  breadcrumbSchema,
  faqSchema,
} from "@/components/seo/JsonLd";
import { BarChart3, Truck, MapPin, Plug, ArrowRight } from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const metadata = buildMetadata({
  title: "Connexx, the multi-carrier shipping platform from ITD",
  description:
    "Connexx is the multi-carrier shipping platform powered by ITD Global. Every order routes to the best-value carrier and gets a label in seconds, with tracking and customs in one place. 17.5 million labels a year across 16 carriers.",
  path: "/connexx",
});

interface ConnexxModule {
  icon: LucideIcon;
  name: string;
  /** Short line for the "What Connexx does" summary grid. */
  summary: string;
  /** One-liner under the module title in the deep-dive. */
  lead: string;
  bullets: string[];
  /** Optional animated preview keyed by name; falls back to the icon placeholder. */
  preview?: "intelligence";
}

const modules: ConnexxModule[] = [
  {
    icon: BarChart3,
    name: "Intelligence",
    summary:
      "A live view of what you're shipping, with problem parcels flagged before your customers chase them.",
    lead: "A live view of everything you ship, with the parcels that need attention surfaced before your customers chase you.",
    bullets: [
      "Label volume broken down by carrier, service, order source and destination, with UK and worldwide delivery maps and CSV export on each view.",
      "Filter by labels printed or all shipments, over 1, 7, 14 or 30 days, or a full year.",
      "The Exceptions view tracks your delivery rate and flags parcels that have gone quiet, so a stuck order shows up before the buyer emails in.",
      "Open exceptions are grouped by who can act on them, so your team goes straight to the ones they can move.",
      "An action queue lists the longest-stuck parcels first, with barcode, carrier, destination and last tracking event.",
    ],
    preview: "intelligence",
  },
  {
    icon: Truck,
    name: "Multi-Carrier Dispatch",
    summary:
      "Labels for the carriers you ship with, from one screen, in whatever format each needs.",
    lead: "One place to dispatch across the carriers you ship with, in the label format and manifest each one needs.",
    bullets: [
      "16 live carrier integrations, UK and international.",
      "One-click label generation, with batch processing for peak volume.",
      "Manifests generated by date range or by shipment IDs.",
      "Failed dispatches are flagged per parcel with the carrier's error, so your team can fix and rebook before the order gets lost in a batch.",
    ],
  },
  {
    icon: MapPin,
    name: "Integrated Tracking",
    summary:
      "One place to track across your carriers, without chasing separate courier sites.",
    lead: "One tracking view across your carriers, with live status pulled straight from the source.",
    bullets: [
      "Live tracking events pulled directly from the carrier APIs, with automatic fallback to stored data when a live feed has nothing new yet.",
      "Each carrier's status codes are normalised into one set, so “Delivered” or “Exception” means the same thing whichever carrier it came from.",
      "A real-time push the moment a label job or batch completes, so no one refreshes a screen to check.",
      "Status updates and tracking codes push to your own systems via webhook, alongside the label and shipment data.",
    ],
  },
  {
    icon: Plug,
    name: "Store & Workflow Connectivity",
    summary:
      "Shopify, eBay, Temu and your own systems connect via API, with rules that route each shipment to the right carrier.",
    lead: "Native integrations where it matters, an API for the rest.",
    bullets: [
      "Native, OAuth-connected integrations with Shopify, eBay and Temu pull orders in and push shipment status back automatically.",
      "A REST API covers shipment creation, cancellation, carrier lookup and tracking, so any system you run can plug straight in.",
      "Routing rules match each shipment to a carrier and service on conditions like weight and warehouse, flagging anything that doesn't fit for review.",
      "Import profiles map incoming order data to Connexx's shipment fields, so a new order source isn't a custom engineering job.",
    ],
  },
];

const faqItems = [
  {
    question: "What is Connexx?",
    answer:
      "Connexx is the multi-carrier shipping platform powered by ITD Global. It connects your sales channels and systems to 16 UK and international carriers from one dashboard. Each order routes to the best-value carrier and gets a label in seconds, with tracking and customs handled in the same place. Behind it sits ITD's carrier network and the team who run it alongside you.",
  },
  {
    question:
      "How does Connexx compare to Shiptheory, Sendcloud, and Metapack?",
    answer:
      "Connexx is UK-built with deeper carrier and customs coverage than Shiptheory, deeper B2B and customs handling than Sendcloud, and a faster onboarding timeline than Metapack. Shiptheory is strong for small UK retailers but limited at scale. Sendcloud is strong in EU eCommerce. Metapack is enterprise-grade and typically over-engineered for businesses under £50m revenue.",
  },
  {
    question: "How long does it take to set up Connexx?",
    answer:
      "Shopify connects in minutes through the native app; eBay and Temu connect via OAuth. Marketplace and multi-channel stacks take a few hours. ERP integrations (such as NetSuite) typically run six to eight weeks for a multi-country enterprise rollout. Import profiles map a new order source to Connexx's shipment fields, so adding a channel is not a custom engineering job.",
  },
  {
    question: "Does Connexx work with my ERP?",
    answer:
      "Likely yes. Connexx has native integrations to Oracle NetSuite, Linnworks, Mintsoft, Veeqo, StoreFeeder, Selro, and ShipHero. Shipment write-back into the ERP is included on every native integration. If your ERP is not on the native list, the REST API supports any system that can call HTTPS and receive webhooks. Request a quote and bring your ERP version number, we will tell you on the call.",
  },
  {
    question: "Does Connexx replace my customs broker?",
    answer:
      "For most parcel shipments, yes. Connexx handles HS code lookup, EORI numbers, IOSS for EU consignments under €150, commercial invoices, packing lists, and country-specific customs declarations against HMRC, EU CDS, and the Windsor Framework. Specialist freight forwarding (FCA, EXW, dangerous goods) still uses your broker. Routine parcel exports to the EU, US, and other Connexx-covered countries are handled inside the platform.",
  },
  {
    question: "What carriers does Connexx support in the UK?",
    answer:
      "Royal Mail (Tracked 24, Tracked 48, Signed, Special Delivery, First Class, Second Class, International), DPD (Next Day, Predict, Two Day, Saturday, DPD Local), Evri (Standard, Next Day, ParcelShop), Parcelforce (Express24, Express48, Global Express, Global Priority, Global Value), DX, InPost, and Amazon Shipping. Every UK postcode is covered, including Highlands and Islands, Channel Islands, Northern Ireland, and BFPO.",
  },
  {
    question: "How does Connexx pricing work?",
    answer:
      "Connexx comes with shipping through ITD. Pricing scales with shipment volume, and setup is scoped to your integration mix (eCommerce only, ERP, marketplaces, or full stack). Get a quote and we will show you the rates you would ship on, and how Connexx runs day to day.",
  },
  {
    question: "Does Connexx have an API?",
    answer:
      "Yes. The Connexx REST API covers shipment creation, cancellation, carrier lookup, and tracking, with webhook events for the full shipment lifecycle. Authentication is bearer token. Full documentation, schema reference, and code samples in cURL, Node, Python, and PHP are at /help/developers.",
  },
];

export default function ConnexxPage() {
  const ldData = [
    productSchema({
      name: "Connexx",
      description:
        "Multi-carrier shipping platform powered by ITD Global. Every order routes to the best-value carrier and gets a label in seconds, with rate comparison, multi-carrier dispatch, integrated tracking, and store and workflow connectivity in one place.",
      path: "/connexx",
      category: "Shipping software",
    }),
    breadcrumbSchema([
      { name: "Home", path: "/" },
      { name: "Connexx", path: "/connexx" },
    ]),
    faqSchema(faqItems),
  ];

  return (
    <>
      <JsonLd data={ldData} />

      {/* Hero */}
      <section data-hero-tone="light" className="bleed-nav relative hero-bg overflow-hidden py-16 md:py-24 lg:py-28">
        <div className="hero-bg-blob" aria-hidden />
        <div className="absolute inset-0 bg-noise pointer-events-none opacity-[0.4] mix-blend-multiply" aria-hidden />
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid items-center gap-8 lg:grid-cols-[minmax(0,0.78fr)_minmax(0,1.22fr)]">
            <div>
              <p className="hero-entrance-h1 text-eyebrow text-accent mb-3">
                The Connexx platform
              </p>
              <h1 className="hero-entrance-h1 text-display-xl text-text-primary">
                The engine behind 17.5 million labels a year
              </h1>
              <p className="hero-entrance-sub mt-5 text-body-lg text-text-secondary max-w-xl">
                A new one every 2.7 seconds, across 16 carriers and used by more
                than 6,000 UK businesses for over 20 years.
              </p>
              <div className="hero-entrance-cta mt-8 flex flex-col sm:flex-row gap-3">
                <MagneticButton>
                  <Button href="/contact?enquiry=connexx-demo">
                    Request a Connexx demo
                  </Button>
                </MagneticButton>
                <Button href={RATE_CHECKER_URL} variant="secondary">
                  Get a quote
                </Button>
              </div>
            </div>

            <div className="hero-entrance-aside">
              <FullOverviewAnimation />
            </div>
          </div>
        </div>
      </section>

      {/* Hero stats strip — matches the hero background for visual continuity */}
      <section className="relative hero-bg overflow-hidden py-10 md:py-12">
        <div className="absolute inset-0 bg-noise pointer-events-none opacity-[0.4] mix-blend-multiply" aria-hidden />
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            <AnimatedCounter end={17.5} decimals={1} suffix="M" label="Labels a year" surface="light" />
            <AnimatedCounter end={16} label="Carriers" surface="light" />
            <AnimatedCounter end={6000} suffix="+" label="UK businesses" surface="light" />
            <AnimatedCounter end={20} suffix="+" label="Years" surface="light" />
          </div>
        </div>
      </section>

      {/* Ecosystem orbit — interactive radar showing what Connexx connects to */}
      <ConnexxOrbit />

      {/* What Connexx does — four-module summary */}
      <section className="bg-bg-secondary py-16 md:py-24">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <ScrollReveal>
            <div className="text-center mb-12">
              <h2 className="text-display-lg text-text-primary">
                What Connexx does
              </h2>
              <p className="mt-3 text-text-secondary max-w-2xl mx-auto">
                Four modules cover the shipment from quote to tracking. Each
                works on its own; together they replace the patchwork of carrier
                portals and tracking tabs an operations team accumulates.
              </p>
            </div>
          </ScrollReveal>

          <div className="grid sm:grid-cols-2 gap-4">
            {modules.map((mod, i) => (
              <ScrollReveal key={mod.name} delay={i * 0.05}>
                <div className="bg-white rounded-xl border border-border p-6 hover:shadow-md hover:border-accent/20 transition-all h-full">
                  <mod.icon className="w-8 h-8 text-accent mb-3" />
                  <p className="text-heading-md text-text-primary">
                    {mod.name}
                  </p>
                  <p className="mt-1.5 text-body-sm text-text-secondary">
                    {mod.summary}
                  </p>
                </div>
              </ScrollReveal>
            ))}
          </div>
        </div>
      </section>

      {/* Feature explorer — in-place switcher across the four modules */}
      <ConnexxFeatures />

      {/* How Connexx integrates */}
      <section className="bg-bg-secondary py-16 md:py-24">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <ScrollReveal>
            <div className="text-center mb-12">
              <h2 className="text-display-lg text-text-primary">
                Connects to everything
              </h2>
              <p className="mt-3 text-text-secondary max-w-2xl mx-auto leading-relaxed">
                Connexx slots into your existing stack. Sales channels send
                orders in. ERPs and WMSs receive shipment data and tracking.
                Marketplaces dispatch under each platform&rsquo;s SLA rules.
                Carriers receive booked shipments and return tracking updates.
              </p>
            </div>
          </ScrollReveal>

          <div className="text-center">
            <Link
              href="/integrations/carriers"
              className="inline-flex items-center gap-1.5 text-sm text-accent font-medium hover:underline"
            >
              Browse Integrations <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <FaqSection
        heading="Eight questions buyers ask"
        subheading=""
        items={faqItems}
      />

      {/* Closing CTA */}
      <ClosingCTA
        headline="Connexx comes with shipping through ITD"
        subtitle="Get a quote and we'll show you the rates you'd ship on, and how Connexx runs day to day."
        primaryCta={{ label: "Get a quote", href: RATE_CHECKER_URL }}
        secondaryCta={{ label: "Contact us", href: "/contact?enquiry=connexx-demo" }}
      />
    </>
  );
}
